using System;using System.Collections.Generic;using System.Net.Http;using System.Net.Http.Headers;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.Dashboard;

/// <summary>Apache Superset connection strategy. HTTP to port 8088 (/api/v1). Modern data exploration platform.</summary>
public sealed class ApacheSupersetConnectionStrategy : DashboardConnectionStrategyBase
{
    public override string StrategyId => "superset";public override string DisplayName => "Apache Superset";public override ConnectionStrategyCapabilities Capabilities => new();public override string SemanticDescription => "Apache Superset modern BI platform. SQL editor, rich visualizations, and enterprise features.";public override string[] Tags => ["superset", "apache", "bi", "open-source", "sql-editor"];
    public ApacheSupersetConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var baseUrl = config.ConnectionString?.TrimEnd('/') ?? throw new ArgumentException("Apache Superset connection string is required, localhost fallback is not allowed in production");var httpClient = new HttpClient { BaseAddress = new Uri(baseUrl), Timeout = config.Timeout };if (config.Properties.TryGetValue("ApiKey", out var apiKey)){httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", apiKey.ToString()!);}return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "Superset", ["BaseUrl"] = baseUrl });}
    protected override async Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct){try { using var response = await handle.GetConnection<HttpClient>().GetAsync("/api/v1/chart/", ct); return response.IsSuccessStatusCode; } catch (OperationCanceledException) { throw; } catch { return false; }}
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override async Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct){var sw = System.Diagnostics.Stopwatch.StartNew();try { using var response = await handle.GetConnection<HttpClient>().GetAsync("/health", ct); sw.Stop(); return new ConnectionHealth(response.IsSuccessStatusCode, response.IsSuccessStatusCode ? "Superset ready" : $"Superset error: HTTP {(int)response.StatusCode}", sw.Elapsed, DateTimeOffset.UtcNow); }catch (OperationCanceledException) { throw; } catch (Exception ex) { sw.Stop(); return new ConnectionHealth(false, ex.Message, sw.Elapsed, DateTimeOffset.UtcNow); }}
    public override async Task<string> ProvisionDashboardAsync(IConnectionHandle handle, string dashboardDefinition, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();using var content = new StringContent(dashboardDefinition, Encoding.UTF8, "application/json");using var response = await httpClient.PostAsync("/api/v1/dashboard/", content, ct);response.EnsureSuccessStatusCode();var result = await response.Content.ReadAsStringAsync(ct);using var json = JsonDocument.Parse(result);return json.RootElement.GetProperty("id").GetInt32().ToString();}
    public override async Task PushDataAsync(IConnectionHandle handle, string datasetId, IReadOnlyList<Dictionary<string, object?>> data, CancellationToken ct = default){var json = JsonSerializer.Serialize(data);using var content = new StringContent(json, Encoding.UTF8, "application/json");using var response = await handle.GetConnection<HttpClient>().PostAsync($"/api/v1/dataset/{Uri.EscapeDataString(datasetId)}", content, ct);response.EnsureSuccessStatusCode();}
}
