using System;using System.Collections.Generic;using System.Net.Http;using System.Net.Http.Headers;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.Dashboard;

/// <summary>Google Looker. HTTPS to *.cloud.looker.com/api. Enterprise BI platform.</summary>
public sealed class GoogleLookerConnectionStrategy : DashboardConnectionStrategyBase
{
    public override string StrategyId => "google-looker";public override string DisplayName => "Google Looker";public override ConnectionStrategyCapabilities Capabilities => new();public override string SemanticDescription => "Google Looker enterprise BI. Semantic modeling with LookML and embedded analytics.";public override string[] Tags => ["looker", "google", "bi", "lookml", "enterprise"];
    public GoogleLookerConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var baseUrl = config.ConnectionString?.TrimEnd('/') ?? throw new ArgumentException("Looker instance URL required");var httpClient = new HttpClient { BaseAddress = new Uri(baseUrl), Timeout = config.Timeout };if (config.Properties.TryGetValue("ApiKey", out var apiKey)){httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", apiKey.ToString()!);}return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "Looker", ["BaseUrl"] = baseUrl });}
    protected override async Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct){try { using var response = await handle.GetConnection<HttpClient>().GetAsync("/api/4.0/alive", ct); return response.IsSuccessStatusCode; } catch (OperationCanceledException) { throw; } catch { return false; }}
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override async Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct){var sw = System.Diagnostics.Stopwatch.StartNew();try { using var response = await handle.GetConnection<HttpClient>().GetAsync("/api/4.0/alive", ct); sw.Stop(); return new ConnectionHealth(response.IsSuccessStatusCode, response.IsSuccessStatusCode ? "Looker ready" : $"Looker error: HTTP {(int)response.StatusCode}", sw.Elapsed, DateTimeOffset.UtcNow); }catch (OperationCanceledException) { throw; } catch (Exception ex) { sw.Stop(); return new ConnectionHealth(false, ex.Message, sw.Elapsed, DateTimeOffset.UtcNow); }}
    public override async Task<string> ProvisionDashboardAsync(IConnectionHandle handle, string dashboardDefinition, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();using var content = new StringContent(dashboardDefinition, Encoding.UTF8, "application/json");using var response = await httpClient.PostAsync("/api/4.0/dashboards", content, ct);response.EnsureSuccessStatusCode();var result = await response.Content.ReadAsStringAsync(ct);using var json = JsonDocument.Parse(result);return json.RootElement.GetProperty("id").GetString() ?? "";}
    public override Task PushDataAsync(IConnectionHandle handle, string datasetId, IReadOnlyList<Dictionary<string, object?>> data, CancellationToken ct = default) => throw new NotSupportedException("Looker queries data sources directly via connections.");
}
