using System;using System.Collections.Generic;using System.Net.Http;using System.Net.Http.Headers;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.Dashboard;

/// <summary>Redash connection strategy. HTTP to port 5000 (/api). Open-source data visualization.</summary>
public sealed class RedashConnectionStrategy : DashboardConnectionStrategyBase
{
    public override string StrategyId => "redash";public override string DisplayName => "Redash";public override ConnectionStrategyCapabilities Capabilities => new();public override string SemanticDescription => "Redash data visualization. Connect to any data source and create interactive dashboards.";public override string[] Tags => ["redash", "visualization", "open-source", "sql", "dashboards"];
    public RedashConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var baseUrl = config.ConnectionString?.TrimEnd('/') ?? "http://localhost:5000";var httpClient = new HttpClient { BaseAddress = new Uri(baseUrl), Timeout = config.Timeout };if (config.Properties.TryGetValue("ApiKey", out var apiKey)){httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Key", apiKey.ToString()!);}return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "Redash", ["BaseUrl"] = baseUrl });}
    protected override async Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct){try { using var response = await handle.GetConnection<HttpClient>().GetAsync("/api/queries", ct); return response.IsSuccessStatusCode; } catch (OperationCanceledException) { throw; } catch { return false; }}
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override async Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct){var sw = System.Diagnostics.Stopwatch.StartNew();try { using var response = await handle.GetConnection<HttpClient>().GetAsync("/ping", ct); sw.Stop(); return new ConnectionHealth(response.IsSuccessStatusCode, response.IsSuccessStatusCode ? "Redash ready" : $"Redash error: HTTP {(int)response.StatusCode}", sw.Elapsed, DateTimeOffset.UtcNow); }catch (OperationCanceledException) { throw; } catch (Exception ex) { sw.Stop(); return new ConnectionHealth(false, ex.Message, sw.Elapsed, DateTimeOffset.UtcNow); }}
    public override async Task<string> ProvisionDashboardAsync(IConnectionHandle handle, string dashboardDefinition, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();using var content = new StringContent(dashboardDefinition, Encoding.UTF8, "application/json");using var response = await httpClient.PostAsync("/api/dashboards", content, ct);response.EnsureSuccessStatusCode();var result = await response.Content.ReadAsStringAsync(ct);using var json = JsonDocument.Parse(result);return json.RootElement.GetProperty("slug").GetString() ?? "";}
    public override async Task PushDataAsync(IConnectionHandle handle, string datasetId, IReadOnlyList<Dictionary<string, object?>> data, CancellationToken ct = default){var json = JsonSerializer.Serialize(data);using var content = new StringContent(json, Encoding.UTF8, "application/json");using var response = await handle.GetConnection<HttpClient>().PostAsync($"/api/queries/{Uri.EscapeDataString(datasetId)}/results", content, ct);response.EnsureSuccessStatusCode();}
}
