using System;using System.Collections.Generic;using System.Net.Http;using System.Net.Http.Headers;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.Dashboard;

/// <summary>Tableau connection strategy. HTTPS REST to Tableau Server/Online. Enterprise BI platform.</summary>
public sealed class TableauConnectionStrategy : DashboardConnectionStrategyBase
{
    public override string StrategyId => "tableau";public override string DisplayName => "Tableau";public override ConnectionStrategyCapabilities Capabilities => new();public override string SemanticDescription => "Tableau enterprise BI platform. Visual analytics, data preparation, and governed self-service BI.";public override string[] Tags => ["tableau", "commercial", "bi", "enterprise", "visual-analytics"];
    public TableauConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var baseUrl = config.ConnectionString?.TrimEnd('/') ?? throw new ArgumentException("Tableau server URL required");var siteId = config.Properties.TryGetValue("SiteId", out var sid) && sid is string s && !string.IsNullOrWhiteSpace(s) ? s : throw new ArgumentException("Tableau SiteId is required. Provide it via connection properties.");var httpClient = new HttpClient { BaseAddress = new Uri(baseUrl), Timeout = config.Timeout };if (config.Properties.TryGetValue("Token", out var token)){httpClient.DefaultRequestHeaders.Add("X-Tableau-Auth", token.ToString()!);}return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "Tableau", ["BaseUrl"] = baseUrl, ["SiteId"] = siteId });}
    protected override async Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct){try { using var response = await handle.GetConnection<HttpClient>().GetAsync("/api/3.20/serverinfo", ct); return response.IsSuccessStatusCode; } catch (OperationCanceledException) { throw; } catch { return false; }}
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override async Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct){var sw = System.Diagnostics.Stopwatch.StartNew();try { using var response = await handle.GetConnection<HttpClient>().GetAsync("/api/3.20/serverinfo", ct); sw.Stop(); return new ConnectionHealth(response.IsSuccessStatusCode, response.IsSuccessStatusCode ? "Tableau ready" : $"Tableau error: HTTP {(int)response.StatusCode}", sw.Elapsed, DateTimeOffset.UtcNow); }catch (OperationCanceledException) { throw; } catch (Exception ex) { sw.Stop(); return new ConnectionHealth(false, ex.Message, sw.Elapsed, DateTimeOffset.UtcNow); }}
    public override async Task<string> ProvisionDashboardAsync(IConnectionHandle handle, string dashboardDefinition, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var siteId = handle.ConnectionInfo.TryGetValue("SiteId", out var sid) ? Uri.EscapeDataString(sid.ToString()!) : throw new InvalidOperationException("SiteId missing from connection handle");using var content = new StringContent(dashboardDefinition, Encoding.UTF8, "application/json");using var response = await httpClient.PostAsync($"/api/3.20/sites/{siteId}/workbooks", content, ct);response.EnsureSuccessStatusCode();var result = await response.Content.ReadAsStringAsync(ct);using var json = JsonDocument.Parse(result);return json.RootElement.GetProperty("workbook").GetProperty("id").GetString() ?? "";}
    public override async Task PushDataAsync(IConnectionHandle handle, string datasetId, IReadOnlyList<Dictionary<string, object?>> data, CancellationToken ct = default){var siteId = handle.ConnectionInfo.TryGetValue("SiteId", out var sid) ? Uri.EscapeDataString(sid.ToString()!) : throw new InvalidOperationException("SiteId missing from connection handle");var json = JsonSerializer.Serialize(data);using var content = new StringContent(json, Encoding.UTF8, "application/json");using var response = await handle.GetConnection<HttpClient>().PostAsync($"/api/3.20/sites/{siteId}/datasources/{Uri.EscapeDataString(datasetId)}/data", content, ct);response.EnsureSuccessStatusCode();}
}
