using System.Text;
using DataWarehouse.SDK.Contracts;

namespace DataWarehouse.SDK.VirtualDiskEngine.FileExtension.OsIntegration;

/// <summary>
/// Builds Windows registry (.reg) files and PowerShell scripts for registering
/// DWVD file type associations, ProgIDs, shell verbs, and MIME mappings.
/// Supports both machine-wide (HKCR) .reg files and per-user (HKCU) PowerShell scripts.
/// </summary>
[SdkCompatibility("6.0.0", Notes = "Phase 79: Windows registry builder (FEXT-02)")]
public static class WindowsRegistryBuilder
{
    private const string RegFileHeader = "Windows Registry Editor Version 5.00";
    private const string HkcrPrefix = "HKEY_CLASSES_ROOT";
    private const string HkcuClassesPrefix = "HKCU:\\Software\\Classes";

    /// <summary>
    /// Generates a complete Windows .reg file containing all DWVD file type registrations.
    /// The file uses UTF-16LE encoding with BOM as required by the Windows Registry Editor.
    /// </summary>
    /// <remarks>
    /// The generated file registers:
    /// <list type="bullet">
    ///   <item><description>Primary .dwvd extension pointing to DataWarehouse.DwvdFile ProgID</description></item>
    ///   <item><description>Shell verbs (Open, Inspect, Verify) with dw CLI commands</description></item>
    ///   <item><description>Default icon, content type, and perceived type</description></item>
    ///   <item><description>All secondary extensions with their own ProgIDs</description></item>
    ///   <item><description>MIME database entry for application/vnd.datawarehouse.dwvd</description></item>
    /// </list>
    /// </remarks>
    /// <param name="dwCliPath">
    /// Path to the dw CLI executable. Defaults to "dw" (assumes it is on PATH).
    /// </param>
    /// <returns>The .reg file content as a string.</returns>
    public static string BuildRegFile(string dwCliPath = "dw")
    {
        var sb = new StringBuilder();
        sb.AppendLine(RegFileHeader);
        sb.AppendLine();

        // --- Primary extension ---
        var primary = WindowsProgId.CreatePrimary();
        AppendRegExtension(sb, primary);
        AppendRegProgId(sb, primary, dwCliPath);

        // --- Secondary extensions ---
        foreach (var kind in SecondaryExtensions.All)
        {
            var secondary = WindowsProgId.CreateForSecondary(kind);
            AppendRegExtension(sb, secondary);
            AppendRegProgId(sb, secondary, dwCliPath);
        }

        // --- MIME database ---
        sb.AppendLine($"; MIME type association for {DwvdMimeType.MimeType}");
        sb.AppendLine($"[{HkcrPrefix}\\MIME\\Database\\Content Type\\{DwvdMimeType.MimeType}]");
        sb.AppendLine($"\"Extension\"=\"{DwvdMimeType.PrimaryExtension}\"");
        sb.AppendLine();

        return sb.ToString();
    }

    /// <summary>
    /// Generates a PowerShell script that registers DWVD file type associations
    /// under HKCU:\Software\Classes (no administrator privileges required).
    /// The script is idempotent and uses <c>-ErrorAction SilentlyContinue</c> for safe re-runs.
    /// </summary>
    /// <param name="dwCliPath">
    /// Path to the dw CLI executable. Defaults to "dw" (assumes it is on PATH).
    /// </param>
    /// <returns>The PowerShell script content as a string.</returns>
    public static string BuildPowerShellScript(string dwCliPath = "dw")
    {
        var sb = new StringBuilder();
        sb.AppendLine("# DataWarehouse DWVD File Type Registration (Current User)");
        sb.AppendLine("# Generated by DataWarehouse SDK - Phase 79 FEXT-02");
        sb.AppendLine("# Run with: powershell -ExecutionPolicy Bypass -File register-dwvd.ps1");
        sb.AppendLine();
        // P2-798: Use 'Stop' so any registry command failure terminates the script with a
        // non-zero exit code. 'SilentlyContinue' silently swallowed errors, making partial
        // registration (e.g., missing keys) undetectable.
        sb.AppendLine("$ErrorActionPreference = 'Stop'");
        sb.AppendLine();

        // --- Primary extension ---
        var primary = WindowsProgId.CreatePrimary();
        AppendPsExtension(sb, primary);
        AppendPsProgId(sb, primary, dwCliPath);

        // --- Secondary extensions ---
        foreach (var kind in SecondaryExtensions.All)
        {
            var secondary = WindowsProgId.CreateForSecondary(kind);
            AppendPsExtension(sb, secondary);
            AppendPsProgId(sb, secondary, dwCliPath);
        }

        // --- MIME association ---
        sb.AppendLine("# MIME type association");
        var mimeKey = $"{HkcuClassesPrefix}\\MIME\\Database\\Content Type\\{DwvdMimeType.MimeType}";
        sb.AppendLine($"New-Item -Path '{mimeKey}' -Force | Out-Null");
        sb.AppendLine($"Set-ItemProperty -Path '{mimeKey}' -Name 'Extension' -Value '{DwvdMimeType.PrimaryExtension}'");
        sb.AppendLine();

        sb.AppendLine("Write-Host 'DWVD file type registration complete.' -ForegroundColor Green");

        return sb.ToString();
    }

    /// <summary>
    /// Generates a .reg file that removes all DWVD file type registrations from HKCR.
    /// Uses the <c>[-HKEY_CLASSES_ROOT\...]</c> syntax to delete entire registry keys.
    /// </summary>
    /// <returns>The uninstall .reg file content as a string.</returns>
    public static string BuildUninstallRegFile()
    {
        var sb = new StringBuilder();
        sb.AppendLine(RegFileHeader);
        sb.AppendLine();
        sb.AppendLine("; Remove all DataWarehouse DWVD file type registrations");
        sb.AppendLine();

        // Primary
        var primary = WindowsProgId.CreatePrimary();
        sb.AppendLine($"[-{HkcrPrefix}\\{primary.Extension}]");
        sb.AppendLine($"[-{HkcrPrefix}\\{primary.ProgId}]");
        sb.AppendLine();

        // Secondary
        foreach (var kind in SecondaryExtensions.All)
        {
            var secondary = WindowsProgId.CreateForSecondary(kind);
            sb.AppendLine($"[-{HkcrPrefix}\\{secondary.Extension}]");
            sb.AppendLine($"[-{HkcrPrefix}\\{secondary.ProgId}]");
        }

        sb.AppendLine();
        sb.AppendLine($"[-{HkcrPrefix}\\MIME\\Database\\Content Type\\{DwvdMimeType.MimeType}]");
        sb.AppendLine();

        return sb.ToString();
    }

    /// <summary>
    /// Generates a PowerShell script that removes all DWVD file type registrations
    /// from HKCU:\Software\Classes.
    /// </summary>
    /// <returns>The uninstall PowerShell script content as a string.</returns>
    public static string BuildUninstallPowerShellScript()
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Remove DataWarehouse DWVD File Type Registration (Current User)");
        sb.AppendLine("# Generated by DataWarehouse SDK - Phase 79 FEXT-02");
        sb.AppendLine();
        sb.AppendLine("$ErrorActionPreference = 'SilentlyContinue'");
        sb.AppendLine();

        // Primary
        var primary = WindowsProgId.CreatePrimary();
        sb.AppendLine($"Remove-Item -Path '{HkcuClassesPrefix}\\{primary.Extension}' -Recurse -Force");
        sb.AppendLine($"Remove-Item -Path '{HkcuClassesPrefix}\\{primary.ProgId}' -Recurse -Force");
        sb.AppendLine();

        // Secondary
        foreach (var kind in SecondaryExtensions.All)
        {
            var secondary = WindowsProgId.CreateForSecondary(kind);
            sb.AppendLine($"Remove-Item -Path '{HkcuClassesPrefix}\\{secondary.Extension}' -Recurse -Force");
            sb.AppendLine($"Remove-Item -Path '{HkcuClassesPrefix}\\{secondary.ProgId}' -Recurse -Force");
        }

        sb.AppendLine();
        sb.AppendLine($"Remove-Item -Path '{HkcuClassesPrefix}\\MIME\\Database\\Content Type\\{DwvdMimeType.MimeType}' -Recurse -Force");
        sb.AppendLine();
        sb.AppendLine("Write-Host 'DWVD file type registration removed.' -ForegroundColor Yellow");

        return sb.ToString();
    }

    /// <summary>
    /// Appends a .reg file extension key mapping extension to ProgID.
    /// </summary>
    private static void AppendRegExtension(StringBuilder sb, WindowsProgId progId)
    {
        sb.AppendLine($"; Extension: {progId.Extension} -> {progId.ProgId}");
        sb.AppendLine($"[{HkcrPrefix}\\{progId.Extension}]");
        sb.AppendLine($"@=\"{progId.ProgId}\"");
        sb.AppendLine($"\"Content Type\"=\"{progId.ContentType}\"");
        sb.AppendLine($"\"PerceivedType\"=\"{progId.PerceivedType}\"");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends .reg file ProgID key with friendly name, icon, and shell verbs.
    /// </summary>
    private static void AppendRegProgId(StringBuilder sb, WindowsProgId progId, string dwCliPath)
    {
        sb.AppendLine($"; ProgID: {progId.ProgId} - {progId.FriendlyTypeName}");
        sb.AppendLine($"[{HkcrPrefix}\\{progId.ProgId}]");
        sb.AppendLine($"@=\"{progId.FriendlyTypeName}\"");
        sb.AppendLine();

        // Default icon
        var iconEscaped = progId.DefaultIcon.Replace("\\", "\\\\", StringComparison.Ordinal);
        sb.AppendLine($"[{HkcrPrefix}\\{progId.ProgId}\\DefaultIcon]");
        sb.AppendLine($"@=\"{iconEscaped}\"");
        sb.AppendLine();

        // Shell verbs
        foreach (var verb in progId.ShellVerbs)
        {
            sb.AppendLine($"[{HkcrPrefix}\\{progId.ProgId}\\shell\\{verb.Name}]");
            if (!verb.IsDefault)
            {
                sb.AppendLine($"@=\"{verb.DisplayName}\"");
            }
            else
            {
                sb.AppendLine($"@=\"{verb.DisplayName}\"");
                // Mark as default verb
                sb.AppendLine();
                sb.AppendLine($"[{HkcrPrefix}\\{progId.ProgId}\\shell]");
                sb.AppendLine($"@=\"{verb.Name}\"");
            }

            sb.AppendLine();
            var commandLine = WindowsShellHandler.GetCommandLine(verb, dwCliPath);
            var commandEscaped = commandLine.Replace("\\", "\\\\", StringComparison.Ordinal);
            sb.AppendLine($"[{HkcrPrefix}\\{progId.ProgId}\\shell\\{verb.Name}\\command]");
            sb.AppendLine($"@=\"{commandEscaped}\"");
            sb.AppendLine();
        }
    }

    /// <summary>
    /// Appends PowerShell commands for extension registration.
    /// </summary>
    private static void AppendPsExtension(StringBuilder sb, WindowsProgId progId)
    {
        sb.AppendLine($"# Extension: {progId.Extension}");
        var extKey = $"{HkcuClassesPrefix}\\{progId.Extension}";
        sb.AppendLine($"New-Item -Path '{extKey}' -Force | Out-Null");
        sb.AppendLine($"Set-ItemProperty -Path '{extKey}' -Name '(Default)' -Value '{progId.ProgId}'");
        sb.AppendLine($"Set-ItemProperty -Path '{extKey}' -Name 'Content Type' -Value '{progId.ContentType}'");
        sb.AppendLine($"Set-ItemProperty -Path '{extKey}' -Name 'PerceivedType' -Value '{progId.PerceivedType}'");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends PowerShell commands for ProgID registration with shell verbs.
    /// </summary>
    private static void AppendPsProgId(StringBuilder sb, WindowsProgId progId, string dwCliPath)
    {
        sb.AppendLine($"# ProgID: {progId.ProgId}");
        var progIdKey = $"{HkcuClassesPrefix}\\{progId.ProgId}";
        sb.AppendLine($"New-Item -Path '{progIdKey}' -Force | Out-Null");
        sb.AppendLine($"Set-ItemProperty -Path '{progIdKey}' -Name '(Default)' -Value '{progId.FriendlyTypeName}'");
        sb.AppendLine();

        // Default icon
        var iconKey = $"{progIdKey}\\DefaultIcon";
        sb.AppendLine($"New-Item -Path '{iconKey}' -Force | Out-Null");
        sb.AppendLine($"Set-ItemProperty -Path '{iconKey}' -Name '(Default)' -Value '{progId.DefaultIcon}'");
        sb.AppendLine();

        // Shell verbs
        foreach (var verb in progId.ShellVerbs)
        {
            var verbKey = $"{progIdKey}\\shell\\{verb.Name}";
            sb.AppendLine($"New-Item -Path '{verbKey}\\command' -Force | Out-Null");
            sb.AppendLine($"Set-ItemProperty -Path '{verbKey}' -Name '(Default)' -Value '{verb.DisplayName}'");

            if (verb.IsDefault)
            {
                var shellKey = $"{progIdKey}\\shell";
                sb.AppendLine($"Set-ItemProperty -Path '{shellKey}' -Name '(Default)' -Value '{verb.Name}'");
            }

            var commandLine = WindowsShellHandler.GetCommandLine(verb, dwCliPath);
            sb.AppendLine($"Set-ItemProperty -Path '{verbKey}\\command' -Name '(Default)' -Value '{commandLine}'");
            sb.AppendLine();
        }
    }
}
