using System;
using System.Buffers;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using DataWarehouse.SDK.Contracts;

namespace DataWarehouse.SDK.VirtualDiskEngine.Preamble;

/// <summary>
/// Generates build scripts, Dockerfiles, and composition files for NativeAOT single-binary
/// publishing of the DW Runtime preamble (VOPT-65).
/// </summary>
/// <remarks>
/// <para>This is a C# helper that emits build scripts -- it does NOT execute any build pipeline.
/// The generated artifacts are consumed by DevOps tooling to produce a NativeAOT binary that is
/// then embedded in the preamble region by <see cref="PreambleWriter"/>.</para>
/// <para>Key generated artifacts:</para>
/// <list type="bullet">
/// <item><description>Bash publish script with NativeAOT flags, size validation, and SHA256 output.</description></item>
/// <item><description>Docker multi-stage build for reproducible NativeAOT compilation.</description></item>
/// <item><description>MSBuild Directory.Build.props for plugin composition (include/exclude).</description></item>
/// <item><description>Estimated size breakdown for capacity planning.</description></item>
/// </list>
/// </remarks>
[SdkCompatibility("6.0.0", Notes = "Phase 91.5 Wave 6: VOPT-65 NativeAOT script generator")]
public sealed class NativeAotScriptGenerator
{
    /// <summary>.NET SDK version used in Docker builds.</summary>
    private const string DotNetSdkVersion = "9.0";

    /// <summary>Cached search values for path separator characters.</summary>
    private static readonly SearchValues<char> PathSeparators = SearchValues.Create("/\\");

    /// <summary>Estimated CoreCLR NativeAOT runtime size range.</summary>
    private const string CoreClrEstimate = "CoreCLR NativeAOT runtime: ~5-8MB";

    /// <summary>Estimated SDK core size range.</summary>
    private const string SdkCoreEstimate = "SDK core: ~3-5MB";

    /// <summary>Estimated per-plugin size range.</summary>
    private const string PerPluginEstimate = "Per plugin (avg): ~200KB-1MB";

    /// <summary>Estimated CLI layer size range.</summary>
    private const string CliLayerEstimate = "CLI layer: ~1-2MB";

    /// <summary>
    /// Generates a bash script that runs <c>dotnet publish</c> with all NativeAOT flags,
    /// validates the output binary size, and prints its SHA256 hash.
    /// </summary>
    /// <param name="spec">The publish specification. Must pass <see cref="NativeAotPublishSpec.Validate"/>.</param>
    /// <returns>A complete bash script as a string.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="spec"/> is <c>null</c>.</exception>
    public string GeneratePublishScript(NativeAotPublishSpec spec)
    {
        if (spec is null)
            throw new ArgumentNullException(nameof(spec));

        spec.Validate();

        var sb = new StringBuilder(2048);
        sb.AppendLine("#!/usr/bin/env bash");
        sb.AppendLine("# NativeAOT publish script for DW Runtime preamble binary (VOPT-65)");
        sb.AppendLine("# Generated by NativeAotScriptGenerator -- do not edit manually.");
        sb.AppendLine("set -euo pipefail");
        sb.AppendLine();

        // Environment variables for cross-compilation
        if (spec.Architecture == TargetArchitecture.Aarch64)
        {
            sb.AppendLine("# Cross-compilation environment for ARM64");
            sb.AppendLine("export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1");
            sb.AppendLine("export CC=aarch64-linux-gnu-gcc");
            sb.AppendLine("export CXX=aarch64-linux-gnu-g++");
            sb.AppendLine();
        }
        else if (spec.Architecture == TargetArchitecture.RiscV64)
        {
            sb.AppendLine("# Cross-compilation environment for RISC-V 64");
            sb.AppendLine("export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1");
            sb.AppendLine("export CC=riscv64-linux-gnu-gcc");
            sb.AppendLine("export CXX=riscv64-linux-gnu-g++");
            sb.AppendLine();
        }

        // Build the dotnet publish command
        sb.AppendLine("echo \"[DW Runtime] Starting NativeAOT publish...\"");
        sb.AppendLine();
        sb.Append("dotnet publish ");
        sb.Append(QuoteBash(spec.ProjectPath));
        sb.AppendLine(" \\");
        sb.AppendLine(CultureInfo.InvariantCulture, $"  -r {spec.RuntimeIdentifier} \\");
        sb.AppendLine("  -c Release \\");
        sb.AppendLine("  -p:PublishAot=true \\");
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"  -p:PublishSingleFile={BoolToLower(spec.EnableSingleFile)} \\");
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"  -p:PublishTrimmed={BoolToLower(spec.EnableTrimming)} \\");
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"  -p:EnableCompressionInSingleFile={BoolToLower(spec.EnableCompression)} \\");
        sb.AppendLine("  -p:InvariantGlobalization=true \\");
        sb.AppendLine("  -p:DebugType=none \\");
        sb.AppendLine("  -p:StripSymbols=true \\");

        // Additional MSBuild properties
        foreach (var kvp in spec.AdditionalMsBuildProperties)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"  -p:{kvp.Key}={kvp.Value} \\");
        }

        sb.AppendLine("  -o ./publish");
        sb.AppendLine();

        // Determine output binary name
        var projectName = ExtractProjectName(spec.ProjectPath);
        var outputBinary = $"./publish/{projectName}";

        // Size validation
        sb.AppendLine("# Validate output binary size");
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"MAX_SIZE={spec.MaxBinarySizeBytes}");
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"BINARY={QuoteBash(outputBinary)}");
        sb.AppendLine();
        sb.AppendLine("if [ ! -f \"$BINARY\" ]; then");
        sb.AppendLine("  echo \"ERROR: Output binary not found at $BINARY\" >&2");
        sb.AppendLine("  exit 1");
        sb.AppendLine("fi");
        sb.AppendLine();
        sb.AppendLine("ACTUAL_SIZE=$(stat --format='%s' \"$BINARY\" 2>/dev/null || stat -f '%z' \"$BINARY\")");
        sb.AppendLine("if [ \"$ACTUAL_SIZE\" -gt \"$MAX_SIZE\" ]; then");
        sb.AppendLine("  echo \"ERROR: Binary size ${ACTUAL_SIZE} bytes exceeds limit ${MAX_SIZE} bytes\" >&2");
        sb.AppendLine("  exit 1");
        sb.AppendLine("fi");
        sb.AppendLine();

        // SHA256 and size output
        sb.AppendLine("# Print SHA256 hash of output binary");
        sb.AppendLine("SHA256=$(sha256sum \"$BINARY\" | awk '{print $1}')");
        sb.AppendLine("echo \"SHA256: $SHA256\"");
        sb.AppendLine();
        sb.AppendLine("# Print final binary size");
        sb.AppendLine("SIZE_MB=$(awk \"BEGIN {printf \\\"%.2f\\\", $ACTUAL_SIZE / 1048576}\")");
        sb.AppendLine("echo \"Binary size: ${SIZE_MB}MB (${ACTUAL_SIZE} bytes)\"");
        sb.AppendLine("echo \"[DW Runtime] NativeAOT publish complete.\"");

        return sb.ToString();
    }

    /// <summary>
    /// Generates an MSBuild <c>Directory.Build.props</c> XML file that conditionally includes
    /// or excludes plugin project references based on the spec's composition settings.
    /// </summary>
    /// <param name="spec">The publish specification containing plugin include/exclude lists.</param>
    /// <returns>An XML string for a <c>Directory.Build.props</c> file.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="spec"/> is <c>null</c>.</exception>
    public string GeneratePluginCompositionFile(NativeAotPublishSpec spec)
    {
        if (spec is null)
            throw new ArgumentNullException(nameof(spec));

        var sb = new StringBuilder(1024);
        sb.AppendLine("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
        sb.AppendLine("<!-- NativeAOT plugin composition file (VOPT-65) -->");
        sb.AppendLine("<!-- Generated by NativeAotScriptGenerator -- do not edit manually. -->");
        sb.AppendLine("<Project>");
        sb.AppendLine();

        // Define composition constants
        sb.AppendLine("  <PropertyGroup>");
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"    <DwIncludeCli>{BoolToMsBuild(spec.IncludeCli)}</DwIncludeCli>");
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"    <DwIncludeGui>{BoolToMsBuild(spec.IncludeGui)}</DwIncludeGui>");
        sb.AppendLine("  </PropertyGroup>");
        sb.AppendLine();

        if (spec.IncludedPlugins.Count > 0)
        {
            // Inclusion mode: only listed plugins are referenced
            sb.AppendLine("  <!-- Inclusion mode: only explicitly listed plugins are compiled in -->");
            sb.AppendLine("  <PropertyGroup>");
            sb.AppendLine("    <DefineConstants>$(DefineConstants);DW_PLUGIN_SUBSET</DefineConstants>");
            sb.AppendLine("  </PropertyGroup>");
            sb.AppendLine();
            sb.AppendLine("  <ItemGroup>");
            foreach (var plugin in spec.IncludedPlugins)
            {
                var safeName = SanitizePluginName(plugin);
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"    <ProjectReference Include=\"../Plugins/{plugin}/{plugin}.csproj\" " +
                    $"Condition=\"'$(DwPluginSubset)' == '' Or '$(DwPluginSubset)' == '{safeName}'\" />");
            }
            sb.AppendLine("  </ItemGroup>");
        }
        else if (spec.ExcludedPlugins.Count > 0)
        {
            // Exclusion mode: all plugins except listed ones
            sb.AppendLine("  <!-- Exclusion mode: all plugins except explicitly excluded ones -->");
            sb.AppendLine("  <PropertyGroup>");
            sb.AppendLine("    <DefineConstants>$(DefineConstants);DW_PLUGIN_EXCLUDE</DefineConstants>");
            sb.AppendLine("  </PropertyGroup>");
            sb.AppendLine();
            sb.AppendLine("  <ItemGroup>");
            foreach (var plugin in spec.ExcludedPlugins)
            {
                var safeName = SanitizePluginName(plugin);
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"    <!-- Excluded: {safeName} -->");
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"    <ProjectReference Remove=\"../Plugins/{plugin}/{plugin}.csproj\" " +
                    $"Condition=\"'$(DwExcludePlugin_{safeName})' != 'false'\" />");
            }
            sb.AppendLine("  </ItemGroup>");
        }
        else
        {
            // Full composition: all plugins
            sb.AppendLine("  <!-- Full composition: all plugins included -->");
            sb.AppendLine("  <PropertyGroup>");
            sb.AppendLine("    <DefineConstants>$(DefineConstants);DW_PLUGIN_FULL</DefineConstants>");
            sb.AppendLine("  </PropertyGroup>");
        }

        sb.AppendLine();

        // CLI conditional inclusion
        sb.AppendLine("  <ItemGroup Condition=\"'$(DwIncludeCli)' == 'true'\">");
        sb.AppendLine("    <ProjectReference Include=\"../DataWarehouse.CLI/DataWarehouse.CLI.csproj\" />");
        sb.AppendLine("  </ItemGroup>");
        sb.AppendLine();

        // GUI conditional inclusion
        sb.AppendLine("  <ItemGroup Condition=\"'$(DwIncludeGui)' == 'true'\">");
        sb.AppendLine("    <ProjectReference Include=\"../DataWarehouse.UI/DataWarehouse.UI.csproj\" />");
        sb.AppendLine("  </ItemGroup>");
        sb.AppendLine();
        sb.AppendLine("</Project>");

        return sb.ToString();
    }

    /// <summary>
    /// Generates a multi-stage Dockerfile for reproducible NativeAOT builds.
    /// The final image uses <c>scratch</c> and contains only the single binary.
    /// </summary>
    /// <param name="spec">The publish specification.</param>
    /// <returns>A Dockerfile as a string.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="spec"/> is <c>null</c>.</exception>
    public string GenerateDockerPublishScript(NativeAotPublishSpec spec)
    {
        if (spec is null)
            throw new ArgumentNullException(nameof(spec));

        spec.Validate();

        var projectName = ExtractProjectName(spec.ProjectPath);

        var sb = new StringBuilder(1024);
        sb.AppendLine("# NativeAOT Docker build for DW Runtime preamble binary (VOPT-65)");
        sb.AppendLine("# Generated by NativeAotScriptGenerator -- do not edit manually.");
        sb.AppendLine();

        // Build stage
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"FROM mcr.microsoft.com/dotnet/sdk:{DotNetSdkVersion} AS build");
        sb.AppendLine();
        sb.AppendLine("# Install NativeAOT prerequisites");
        sb.AppendLine("RUN apt-get update && apt-get install -y --no-install-recommends \\");
        sb.AppendLine("    clang \\");
        sb.AppendLine("    zlib1g-dev \\");

        // Cross-compilation tools for non-x64 targets
        if (spec.Architecture == TargetArchitecture.Aarch64)
        {
            sb.AppendLine("    gcc-aarch64-linux-gnu \\");
            sb.AppendLine("    g++-aarch64-linux-gnu \\");
            sb.AppendLine("    binutils-aarch64-linux-gnu \\");
        }
        else if (spec.Architecture == TargetArchitecture.RiscV64)
        {
            sb.AppendLine("    gcc-riscv64-linux-gnu \\");
            sb.AppendLine("    g++-riscv64-linux-gnu \\");
            sb.AppendLine("    binutils-riscv64-linux-gnu \\");
        }

        sb.AppendLine("  && rm -rf /var/lib/apt/lists/*");
        sb.AppendLine();

        // Copy solution
        sb.AppendLine("WORKDIR /src");
        sb.AppendLine("COPY . .");
        sb.AppendLine();

        // Restore and publish
        sb.AppendLine("RUN dotnet restore");
        sb.AppendLine();

        sb.Append("RUN dotnet publish ");
        sb.Append(QuoteBash(spec.ProjectPath));
        sb.AppendLine(" \\");
        sb.AppendLine(CultureInfo.InvariantCulture, $"  -r {spec.RuntimeIdentifier} \\");
        sb.AppendLine("  -c Release \\");
        sb.AppendLine("  -p:PublishAot=true \\");
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"  -p:PublishSingleFile={BoolToLower(spec.EnableSingleFile)} \\");
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"  -p:PublishTrimmed={BoolToLower(spec.EnableTrimming)} \\");
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"  -p:EnableCompressionInSingleFile={BoolToLower(spec.EnableCompression)} \\");
        sb.AppendLine("  -p:InvariantGlobalization=true \\");
        sb.AppendLine("  -p:DebugType=none \\");
        sb.AppendLine("  -p:StripSymbols=true \\");

        foreach (var kvp in spec.AdditionalMsBuildProperties)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"  -p:{kvp.Key}={kvp.Value} \\");
        }

        sb.AppendLine("  -o /app/publish");
        sb.AppendLine();

        // Size validation in build stage
        sb.AppendLine("# Validate binary size");
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"RUN ACTUAL_SIZE=$(stat --format='%s' /app/publish/{projectName}) && \\");
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"    if [ \"$ACTUAL_SIZE\" -gt {spec.MaxBinarySizeBytes} ]; then \\");
        sb.AppendLine("      echo \"ERROR: Binary size $ACTUAL_SIZE exceeds limit\" >&2 && exit 1; \\");
        sb.AppendLine("    fi && \\");
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"    echo \"Binary size: ${{ACTUAL_SIZE}} bytes\" && \\");
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"    sha256sum /app/publish/{projectName}");
        sb.AppendLine();

        // Final stage: scratch with only the binary
        sb.AppendLine("# Final stage: minimal image with only the NativeAOT binary");
        sb.AppendLine("FROM scratch");
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"COPY --from=build /app/publish/{projectName} /dw-runtime");
        sb.AppendLine("ENTRYPOINT [\"/dw-runtime\"]");

        return sb.ToString();
    }

    /// <summary>
    /// Returns estimated size contributions for each component as informational strings.
    /// Useful for capacity planning and validating <see cref="NativeAotPublishSpec.MaxBinarySizeBytes"/>.
    /// </summary>
    /// <param name="spec">The publish specification to estimate sizes for.</param>
    /// <returns>A list of human-readable size estimate strings.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="spec"/> is <c>null</c>.</exception>
    public IReadOnlyList<string> EstimateSizeBreakdown(NativeAotPublishSpec spec)
    {
        if (spec is null)
            throw new ArgumentNullException(nameof(spec));

        var estimates = new List<string>(8);

        // Base runtime
        estimates.Add(CoreClrEstimate);
        estimates.Add(SdkCoreEstimate);

        // Plugin count
        var pluginCount = spec.IncludedPlugins.Count > 0
            ? spec.IncludedPlugins.Count
            : 52; // Full composition: all 52 plugins

        estimates.Add(PerPluginEstimate);
        estimates.Add(string.Create(CultureInfo.InvariantCulture,
            $"Plugin count: {pluginCount} plugins"));

        // CLI layer
        if (spec.IncludeCli)
        {
            estimates.Add(CliLayerEstimate);
        }

        // GUI layer
        if (spec.IncludeGui)
        {
            estimates.Add("GUI layer: ~3-5MB");
        }

        // Compute estimate
        // CoreCLR: ~6.5MB avg, SDK: ~4MB avg, per plugin: ~600KB avg, CLI: ~1.5MB avg, GUI: ~4MB avg
        var estimatedMb = 6.5 + 4.0 + (pluginCount * 0.6);
        if (spec.IncludeCli)
            estimatedMb += 1.5;
        if (spec.IncludeGui)
            estimatedMb += 4.0;

        // Trimming typically saves 30-50%
        if (spec.EnableTrimming)
        {
            estimatedMb *= 0.6; // ~40% reduction
            estimates.Add("Trimming savings: ~40% estimated reduction");
        }

        // Compression typically saves another 10-20%
        if (spec.EnableCompression)
        {
            estimatedMb *= 0.85; // ~15% reduction
            estimates.Add("Compression savings: ~15% estimated reduction");
        }

        estimates.Add(string.Create(CultureInfo.InvariantCulture,
            $"Estimated total: {estimatedMb:F1}MB"));

        // Warning if estimated size exceeds limit
        var estimatedBytes = (long)(estimatedMb * 1024 * 1024);
        if (estimatedBytes > spec.MaxBinarySizeBytes)
        {
            var limitMb = spec.MaxBinarySizeBytes / (1024.0 * 1024.0);
            estimates.Add(string.Format(CultureInfo.InvariantCulture,
                "WARNING: Estimated size ({0:F1}MB) exceeds limit ({1:F1}MB). " +
                "Consider reducing plugin count or enabling trimming.",
                estimatedMb, limitMb));
        }

        return estimates;
    }

    /// <summary>Converts a boolean to lowercase string for MSBuild property values.</summary>
    private static string BoolToLower(bool value) => value ? "true" : "false";

    /// <summary>Converts a boolean to MSBuild-style capitalized string.</summary>
    private static string BoolToMsBuild(bool value) => value ? "true" : "false";

    /// <summary>Wraps a path in double quotes for bash, escaping internal double quotes.</summary>
    private static string QuoteBash(string path) =>
        "\"" + path.Replace("\"", "\\\"", StringComparison.Ordinal) + "\"";

    /// <summary>
    /// Extracts the project name (without extension) from a .csproj path.
    /// Falls back to "DwRuntime" if extraction fails.
    /// </summary>
    private static string ExtractProjectName(string projectPath)
    {
        if (string.IsNullOrEmpty(projectPath))
            return "DwRuntime";

        var fileName = projectPath;

        // Handle both forward and back slashes
        var lastSlash = fileName.AsSpan().LastIndexOfAny(PathSeparators);
        if (lastSlash >= 0)
            fileName = fileName.Substring(lastSlash + 1);

        // Remove .csproj extension
        if (fileName.EndsWith(".csproj", StringComparison.OrdinalIgnoreCase))
            fileName = fileName.Substring(0, fileName.Length - 7);

        return string.IsNullOrEmpty(fileName) ? "DwRuntime" : fileName;
    }

    /// <summary>
    /// Sanitizes a plugin name for use in MSBuild property names by removing dots and hyphens.
    /// </summary>
    private static string SanitizePluginName(string pluginName)
    {
        if (string.IsNullOrEmpty(pluginName))
            return "Unknown";

        return pluginName
            .Replace(".", string.Empty, StringComparison.Ordinal)
            .Replace("-", string.Empty, StringComparison.Ordinal);
    }
}
