using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DataWarehouse.SDK.Contracts.Interface;

/// <summary>
/// Generates a GraphQL Schema Definition Language (SDL) string from a <see cref="DynamicApiModel"/>.
/// Produces Query, Mutation, and Subscription types with Connection-based pagination for lists.
/// </summary>
/// <remarks>
/// <para>Type mapping from API model to GraphQL:</para>
/// <list type="bullet">
///   <item><description>string -> String</description></item>
///   <item><description>int -> Int</description></item>
///   <item><description>long -> BigInt (custom scalar)</description></item>
///   <item><description>bool -> Boolean</description></item>
///   <item><description>datetime -> DateTime (custom scalar)</description></item>
///   <item><description>bytes -> String (base64-encoded)</description></item>
///   <item><description>object -> JSON (custom scalar)</description></item>
/// </list>
/// <para>All list queries return Connection types with edges, pageInfo, and totalCount.</para>
/// </remarks>
public sealed class GraphQlSchemaGenerator
{
    /// <summary>
    /// Generates a complete GraphQL SDL schema from the dynamic API model.
    /// </summary>
    /// <param name="model">The API model to generate from.</param>
    /// <returns>The GraphQL SDL schema as a string.</returns>
    public string GenerateSchema(DynamicApiModel model)
    {
        ArgumentNullException.ThrowIfNull(model);

        var sb = new StringBuilder(8192);

        WriteHeader(sb);
        WriteCustomScalars(sb);
        WriteSchemaDefinition(sb);
        WriteQueryType(sb, model);
        WriteMutationType(sb, model);
        WriteSubscriptionType(sb, model);
        WriteObjectTypes(sb, model);
        WritePaginationTypes(sb);
        WriteCommonTypes(sb);

        return sb.ToString();
    }

    private static void WriteHeader(StringBuilder sb)
    {
        sb.AppendLine("# Auto-generated by DataWarehouse DynamicApiGenerator");
        sb.AppendLine("# DO NOT EDIT - regenerated when plugin capabilities change");
        sb.AppendLine();
    }

    private static void WriteCustomScalars(StringBuilder sb)
    {
        sb.AppendLine("scalar DateTime");
        sb.AppendLine("scalar BigInt");
        sb.AppendLine("scalar JSON");
        sb.AppendLine("scalar Base64");
        sb.AppendLine();
    }

    private static void WriteSchemaDefinition(StringBuilder sb)
    {
        sb.AppendLine("schema {");
        sb.AppendLine("  query: Query");
        sb.AppendLine("  mutation: Mutation");
        sb.AppendLine("  subscription: Subscription");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void WriteQueryType(StringBuilder sb, DynamicApiModel model)
    {
        sb.AppendLine("type Query {");

        // Read operations: GET endpoints become queries
        var getEndpoints = model.Endpoints.Where(e => e.Method == HttpMethod.GET && !e.IsStreaming);
        foreach (var ep in getEndpoints)
        {
            var fieldName = ToFieldName(ep.CapabilityName);
            var args = BuildArguments(ep);
            var returnType = ep.ResponseBody != null
                ? ToGraphQlTypeName(ep.ResponseBody.Name)
                : "JSON";

            sb.AppendLine($"  \"\"\"");
            sb.AppendLine($"  {ep.Description ?? ep.CapabilityName}");
            sb.AppendLine($"  Plugin: {ep.PluginId}");
            sb.AppendLine($"  \"\"\"");
            sb.AppendLine($"  {fieldName}{args}: {returnType}");
            sb.AppendLine();
        }

        // List/search operations return Connection types
        var queryEndpoints = model.Endpoints.Where(e =>
            e.Method == HttpMethod.POST &&
            (e.CapabilityName.Contains("query", StringComparison.OrdinalIgnoreCase) ||
             e.CapabilityName.Contains("search", StringComparison.OrdinalIgnoreCase) ||
             e.CapabilityName.Contains("execute", StringComparison.OrdinalIgnoreCase)) &&
            !e.IsStreaming);

        foreach (var ep in queryEndpoints)
        {
            var fieldName = ToFieldName(ep.CapabilityName) + "Results";
            sb.AppendLine($"  \"\"\"");
            sb.AppendLine($"  {ep.Description ?? ep.CapabilityName}");
            sb.AppendLine($"  \"\"\"");
            sb.AppendLine($"  {fieldName}(query: String!, parameters: JSON, first: Int, after: String): ResultConnection");
            sb.AppendLine();
        }

        // System queries
        sb.AppendLine("  \"\"\"List all available capabilities across all plugins\"\"\"");
        sb.AppendLine("  capabilities(category: String, pluginId: String): [Capability!]!");
        sb.AppendLine();
        sb.AppendLine("  \"\"\"Get system health and statistics\"\"\"");
        sb.AppendLine("  systemHealth: SystemHealth!");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void WriteMutationType(StringBuilder sb, DynamicApiModel model)
    {
        sb.AppendLine("type Mutation {");

        // Write operations: POST (non-query), PUT, DELETE become mutations
        var writeEndpoints = model.Endpoints.Where(e =>
            (e.Method == HttpMethod.POST || e.Method == HttpMethod.PUT || e.Method == HttpMethod.DELETE) &&
            !e.CapabilityName.Contains("query", StringComparison.OrdinalIgnoreCase) &&
            !e.CapabilityName.Contains("search", StringComparison.OrdinalIgnoreCase) &&
            !e.IsStreaming);

        foreach (var ep in writeEndpoints)
        {
            var fieldName = ToMutationName(ep);
            var args = BuildMutationArguments(ep);
            var returnType = ep.ResponseBody != null
                ? ToGraphQlTypeName(ep.ResponseBody.Name)
                : "MutationResult";

            sb.AppendLine($"  \"\"\"");
            sb.AppendLine($"  {ep.Description ?? ep.CapabilityName}");
            sb.AppendLine($"  Plugin: {ep.PluginId}");
            sb.AppendLine($"  \"\"\"");
            sb.AppendLine($"  {fieldName}{args}: {returnType}");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void WriteSubscriptionType(StringBuilder sb, DynamicApiModel model)
    {
        sb.AppendLine("type Subscription {");

        // Streaming endpoints become subscriptions
        var streamingEndpoints = model.Endpoints.Where(e => e.IsStreaming);
        foreach (var ep in streamingEndpoints)
        {
            var fieldName = ToFieldName(ep.CapabilityName) + "Events";
            sb.AppendLine($"  \"\"\"");
            sb.AppendLine($"  Real-time events for {ep.Description ?? ep.CapabilityName}");
            sb.AppendLine($"  Plugin: {ep.PluginId}");
            sb.AppendLine($"  \"\"\"");
            sb.AppendLine($"  {fieldName}(pluginId: String): StreamEvent!");
            sb.AppendLine();
        }

        // System-level subscriptions
        sb.AppendLine("  \"\"\"Subscribe to capability change events\"\"\"");
        sb.AppendLine("  capabilityChanged: CapabilityChangeEvent!");
        sb.AppendLine();
        sb.AppendLine("  \"\"\"Subscribe to plugin lifecycle events\"\"\"");
        sb.AppendLine("  pluginEvent: PluginEvent!");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void WriteObjectTypes(StringBuilder sb, DynamicApiModel model)
    {
        var writtenTypes = new HashSet<string>();

        foreach (var dataType in model.DataTypes)
        {
            if (writtenTypes.Add(dataType.Name))
            {
                WriteObjectType(sb, dataType);
            }
        }

        // Also write types referenced by endpoints
        foreach (var ep in model.Endpoints)
        {
            if (ep.RequestBody != null && writtenTypes.Add(ep.RequestBody.Name))
            {
                WriteInputType(sb, ep.RequestBody);
            }
            if (ep.ResponseBody != null && writtenTypes.Add(ep.ResponseBody.Name))
            {
                WriteObjectType(sb, ep.ResponseBody);
            }
        }
    }

    private static void WriteObjectType(StringBuilder sb, ApiDataType dataType)
    {
        var typeName = ToGraphQlTypeName(dataType.Name);
        if (dataType.Description != null)
        {
            sb.AppendLine($"\"\"\"{dataType.Description}\"\"\"");
        }
        sb.AppendLine($"type {typeName} {{");

        foreach (var prop in dataType.Properties.Values)
        {
            var gqlType = MapToGraphQlType(prop.Type, prop.Nullable);
            if (prop.Description != null)
            {
                sb.AppendLine($"  \"\"\"{prop.Description}\"\"\"");
            }
            sb.AppendLine($"  {ToCamelCase(prop.Name)}: {gqlType}");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void WriteInputType(StringBuilder sb, ApiDataType dataType)
    {
        var typeName = ToGraphQlTypeName(dataType.Name) + "Input";
        if (dataType.Description != null)
        {
            sb.AppendLine($"\"\"\"{dataType.Description}\"\"\"");
        }
        sb.AppendLine($"input {typeName} {{");

        foreach (var prop in dataType.Properties.Values)
        {
            var gqlType = MapToGraphQlType(prop.Type, true); // All input fields nullable
            sb.AppendLine($"  {ToCamelCase(prop.Name)}: {gqlType}");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void WritePaginationTypes(StringBuilder sb)
    {
        sb.AppendLine("\"\"\"Relay-style connection for paginated results\"\"\"");
        sb.AppendLine("type ResultConnection {");
        sb.AppendLine("  edges: [ResultEdge!]!");
        sb.AppendLine("  pageInfo: PageInfo!");
        sb.AppendLine("  totalCount: BigInt!");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("type ResultEdge {");
        sb.AppendLine("  node: JSON!");
        sb.AppendLine("  cursor: String!");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("type PageInfo {");
        sb.AppendLine("  hasNextPage: Boolean!");
        sb.AppendLine("  hasPreviousPage: Boolean!");
        sb.AppendLine("  startCursor: String");
        sb.AppendLine("  endCursor: String");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void WriteCommonTypes(StringBuilder sb)
    {
        sb.AppendLine("\"\"\"Result of a mutation operation\"\"\"");
        sb.AppendLine("type MutationResult {");
        sb.AppendLine("  success: Boolean!");
        sb.AppendLine("  message: String");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("\"\"\"A registered plugin capability\"\"\"");
        sb.AppendLine("type Capability {");
        sb.AppendLine("  capabilityId: String!");
        sb.AppendLine("  displayName: String!");
        sb.AppendLine("  description: String");
        sb.AppendLine("  category: String!");
        sb.AppendLine("  pluginId: String!");
        sb.AppendLine("  pluginName: String!");
        sb.AppendLine("  isAvailable: Boolean!");
        sb.AppendLine("  tags: [String!]!");
        sb.AppendLine("  priority: Int!");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("\"\"\"System health information\"\"\"");
        sb.AppendLine("type SystemHealth {");
        sb.AppendLine("  totalCapabilities: Int!");
        sb.AppendLine("  availableCapabilities: Int!");
        sb.AppendLine("  registeredPlugins: Int!");
        sb.AppendLine("  uptimeSeconds: BigInt!");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("\"\"\"A streaming event from a WebSocket channel\"\"\"");
        sb.AppendLine("type StreamEvent {");
        sb.AppendLine("  type: String!");
        sb.AppendLine("  channel: String!");
        sb.AppendLine("  payload: JSON!");
        sb.AppendLine("  timestamp: DateTime!");
        sb.AppendLine("  correlationId: String");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("\"\"\"Event emitted when a capability changes\"\"\"");
        sb.AppendLine("type CapabilityChangeEvent {");
        sb.AppendLine("  capabilityId: String!");
        sb.AppendLine("  changeType: String!");
        sb.AppendLine("  pluginId: String!");
        sb.AppendLine("  timestamp: DateTime!");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("\"\"\"Plugin lifecycle event\"\"\"");
        sb.AppendLine("type PluginEvent {");
        sb.AppendLine("  pluginId: String!");
        sb.AppendLine("  eventType: String!");
        sb.AppendLine("  timestamp: DateTime!");
        sb.AppendLine("  details: JSON");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    #region Naming Helpers

    private static string MapToGraphQlType(string apiType, bool nullable)
    {
        var baseType = apiType.ToLowerInvariant() switch
        {
            "string" => "String",
            "int" => "Int",
            "long" => "BigInt",
            "bool" => "Boolean",
            "datetime" => "DateTime",
            "bytes" => "Base64",
            "object" => "JSON",
            "array" => "[JSON]",
            _ => "String"
        };

        return nullable ? baseType : $"{baseType}!";
    }

    private static string ToFieldName(string capabilityName)
    {
        var parts = capabilityName.Split('.', '-', '_');
        if (parts.Length == 0) return capabilityName;

        var sb = new StringBuilder();
        for (int i = 0; i < parts.Length; i++)
        {
            var part = parts[i];
            if (part.Length == 0) continue;
            if (i == 0)
            {
                sb.Append(char.ToLowerInvariant(part[0]));
            }
            else
            {
                sb.Append(char.ToUpperInvariant(part[0]));
            }
            if (part.Length > 1) sb.Append(part[1..]);
        }
        return sb.ToString();
    }

    private static string ToMutationName(ApiEndpoint ep)
    {
        var prefix = ep.Method switch
        {
            HttpMethod.POST => "create",
            HttpMethod.PUT => "update",
            HttpMethod.DELETE => "delete",
            _ => "execute"
        };

        var parts = ep.CapabilityName.Split('.', '-', '_');
        var suffix = string.Concat(parts.Select(p =>
            p.Length == 0 ? "" : char.ToUpperInvariant(p[0]) + (p.Length > 1 ? p[1..] : "")));

        return prefix + suffix;
    }

    private static string BuildArguments(ApiEndpoint ep)
    {
        if (ep.Parameters.Count == 0) return "";

        var args = ep.Parameters.Select(p =>
        {
            var gqlType = MapToGraphQlType(p.Type, !p.Required);
            return $"{ToCamelCase(p.Name)}: {gqlType}";
        });

        return $"({string.Join(", ", args)})";
    }

    private static string BuildMutationArguments(ApiEndpoint ep)
    {
        var args = new List<string>();

        foreach (var param in ep.Parameters)
        {
            var gqlType = MapToGraphQlType(param.Type, !param.Required);
            args.Add($"{ToCamelCase(param.Name)}: {gqlType}");
        }

        if (ep.RequestBody != null)
        {
            args.Add($"input: {ToGraphQlTypeName(ep.RequestBody.Name)}Input");
        }

        return args.Count > 0 ? $"({string.Join(", ", args)})" : "";
    }

    private static string ToGraphQlTypeName(string name)
    {
        // Ensure PascalCase
        var parts = name.Split('.', '-', '_');
        return string.Concat(parts.Select(p =>
            p.Length == 0 ? "" : char.ToUpperInvariant(p[0]) + (p.Length > 1 ? p[1..] : "")));
    }

    private static string ToCamelCase(string input)
    {
        if (string.IsNullOrEmpty(input)) return input;
        return char.ToLowerInvariant(input[0]) + (input.Length > 1 ? input[1..] : "");
    }

    #endregion
}
