namespace DataWarehouse.SDK.Compliance;

/// <summary>
/// Status of a compliance passport indicating its current validity and lifecycle state.
/// A passport transitions through these states as it is issued, reviewed, and maintained.
/// </summary>
public enum PassportStatus
{
    /// <summary>Passport is valid and currently active</summary>
    Active,

    /// <summary>Passport has passed its expiration date and requires renewal</summary>
    Expired,

    /// <summary>Passport has been permanently revoked and cannot be reactivated</summary>
    Revoked,

    /// <summary>Passport is temporarily suspended pending investigation or update</summary>
    Suspended,

    /// <summary>Passport is under review and awaiting compliance assessment</summary>
    PendingReview,

    /// <summary>Passport is provisionally issued with limited validity, pending full certification</summary>
    Provisional
}

/// <summary>
/// Scope of a compliance passport, defining the breadth of certification coverage.
/// Determines whether the passport certifies a single object, collection, tenant, or system.
/// </summary>
public enum PassportScope
{
    /// <summary>Passport certifies a single data object</summary>
    Object,

    /// <summary>Passport certifies an entire collection of objects</summary>
    Collection,

    /// <summary>Passport certifies all data within a tenant boundary</summary>
    Tenant,

    /// <summary>Passport certifies system-wide compliance across all tenants</summary>
    System,

    /// <summary>Passport certifies compliance for cross-border data transfers</summary>
    CrossBorder
}

/// <summary>
/// Type of evidence that supports a compliance passport entry.
/// Each evidence type represents a different method of verifying compliance.
/// </summary>
public enum EvidenceType
{
    /// <summary>Evidence generated by automated compliance checking systems</summary>
    AutomatedCheck,

    /// <summary>Evidence from manual audit performed by a human auditor</summary>
    ManualAudit,

    /// <summary>Evidence based on a chain of digital certificates</summary>
    CertificateChain,

    /// <summary>Evidence using zero-knowledge cryptographic proofs for privacy-preserving verification</summary>
    ZeroKnowledgeProof,

    /// <summary>Evidence from a formal attestation report (e.g., SOC 2 Type II)</summary>
    AttestationReport,

    /// <summary>Evidence from an independent third-party verification entity</summary>
    ThirdPartyVerification,

    /// <summary>Evidence from ongoing continuous monitoring and real-time compliance checks</summary>
    ContinuousMonitoring
}

/// <summary>
/// Action to be taken by a sovereignty zone when evaluating a data operation.
/// Defines the enforcement response for zone policy violations or approvals.
/// </summary>
public enum ZoneAction
{
    /// <summary>Allow the operation to proceed without additional requirements</summary>
    Allow,

    /// <summary>Deny the operation entirely</summary>
    Deny,

    /// <summary>Require explicit approval from an authorized party before proceeding</summary>
    RequireApproval,

    /// <summary>Require data to be encrypted before the operation can proceed</summary>
    RequireEncryption,

    /// <summary>Require data to be anonymized or pseudonymized before proceeding</summary>
    RequireAnonymization,

    /// <summary>Place the data in quarantine for further review before allowing the operation</summary>
    Quarantine
}

/// <summary>
/// Decision outcome for a cross-border data transfer request.
/// Represents the result of evaluating transfer legality and compliance.
/// </summary>
public enum TransferDecision
{
    /// <summary>Transfer is approved and may proceed</summary>
    Approved,

    /// <summary>Transfer is denied and must not proceed</summary>
    Denied,

    /// <summary>Transfer is conditionally approved, subject to specified requirements</summary>
    ConditionalApproval,

    /// <summary>Transfer is pending a bilateral or multilateral data transfer agreement</summary>
    PendingAgreement,

    /// <summary>Transfer requires escalation to a data protection officer or authority</summary>
    EscalationRequired
}

/// <summary>
/// Reason for revoking a compliance passport.
/// Provides audit trail context for why a passport was revoked.
/// </summary>
public enum PassportRevocationReason
{
    /// <summary>Passport expired and was not renewed within the grace period</summary>
    Expired,

    /// <summary>Organizational or regulatory policy changed, invalidating the passport</summary>
    PolicyChange,

    /// <summary>Security breach detected that compromises the certified compliance state</summary>
    SecurityBreach,

    /// <summary>Regulatory requirements updated, requiring re-certification</summary>
    RegulatoryUpdate,

    /// <summary>Passport was manually revoked by an administrator or compliance officer</summary>
    ManualRevocation,

    /// <summary>Ongoing compliance monitoring detected a compliance failure</summary>
    ComplianceFailure
}
