using System;using System.Collections.Generic;using System.Net.Http;using System.Net.Http.Headers;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.Observability;

/// <summary>GCP Cloud Monitoring connection strategy. HTTPS to monitoring.googleapis.com. Google Cloud native monitoring.</summary>
public sealed class GcpCloudMonitoringConnectionStrategy : ObservabilityConnectionStrategyBase
{
    public override string StrategyId => "gcp-monitoring";public override string DisplayName => "GCP Cloud Monitoring";public override ConnectionStrategyCapabilities Capabilities => new();public override string SemanticDescription => "GCP Cloud Monitoring (formerly Stackdriver). Metrics, logs, and traces for Google Cloud resources.";public override string[] Tags => ["gcp", "monitoring", "stackdriver", "observability", "cloud"];
    public GcpCloudMonitoringConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var baseUrl = config.ConnectionString?.TrimEnd('/') ?? "https://monitoring.googleapis.com";var httpClient = new HttpClient { BaseAddress = new Uri(baseUrl), Timeout = config.Timeout };if (config.Properties.TryGetValue("ApiKey", out var apiKey)){httpClient.DefaultRequestHeaders.Add("X-Goog-Api-Key", apiKey.ToString()!);}return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "GCPMonitoring", ["BaseUrl"] = baseUrl });}
    protected override Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct) => Task.FromResult(true);
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct) => Task.FromResult(new ConnectionHealth(true, "GCP Monitoring configured", TimeSpan.Zero, DateTimeOffset.UtcNow));
    public override async Task PushMetricsAsync(IConnectionHandle handle, IReadOnlyList<Dictionary<string, object>> metrics, CancellationToken ct = default){var json = JsonSerializer.Serialize(new { timeSeries = metrics });var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await handle.GetConnection<HttpClient>().PostAsync("/v3/projects/PROJECT_ID/timeSeries", content, ct);response.EnsureSuccessStatusCode();}
    public override async Task PushLogsAsync(IConnectionHandle handle, IReadOnlyList<Dictionary<string, object>> logs, CancellationToken ct = default){var json = JsonSerializer.Serialize(new { entries = logs });var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await handle.GetConnection<HttpClient>().PostAsync("/v2/entries:write", content, ct);response.EnsureSuccessStatusCode();}
    public override async Task PushTracesAsync(IConnectionHandle handle, IReadOnlyList<Dictionary<string, object>> traces, CancellationToken ct = default){var json = JsonSerializer.Serialize(new { spans = traces });var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await handle.GetConnection<HttpClient>().PostAsync("/v2/projects/PROJECT_ID/traces:batchWrite", content, ct);response.EnsureSuccessStatusCode();}
}
