using System;using System.Collections.Generic;using System.Net.Http;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.Observability;

/// <summary>Instana connection strategy. HTTPS to *.instana.io. Automatic APM for cloud-native applications.</summary>
public sealed class InstanaConnectionStrategy : ObservabilityConnectionStrategyBase
{
    public override string StrategyId => "instana";public override string DisplayName => "Instana";public override ConnectionStrategyCapabilities Capabilities => new();public override string SemanticDescription => "Instana automatic APM. Auto-discovery, 1-second granularity, and AI-powered incident detection.";public override string[] Tags => ["instana", "commercial", "apm", "auto-discovery", "cloud-native", "ai"];
    public InstanaConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var baseUrl = config.ConnectionString?.TrimEnd('/') ?? throw new ArgumentException("Instana backend URL required");var httpClient = new HttpClient { BaseAddress = new Uri(baseUrl), Timeout = config.Timeout };if (config.Properties.TryGetValue("ApiToken", out var token)){httpClient.DefaultRequestHeaders.Add("Authorization", $"apiToken {token}");}return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "Instana", ["BaseUrl"] = baseUrl });}
    protected override async Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct){try { var response = await handle.GetConnection<HttpClient>().GetAsync("/api/infrastructure-monitoring/snapshots", ct); return response.IsSuccessStatusCode; } catch { return false; }}
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override async Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct){var sw = System.Diagnostics.Stopwatch.StartNew();try { var response = await handle.GetConnection<HttpClient>().GetAsync("/api/infrastructure-monitoring/snapshots", ct); sw.Stop(); return new ConnectionHealth(response.IsSuccessStatusCode, "Instana ready", sw.Elapsed, DateTimeOffset.UtcNow); }catch (Exception ex) { sw.Stop(); return new ConnectionHealth(false, ex.Message, sw.Elapsed, DateTimeOffset.UtcNow); }}
    public override async Task PushMetricsAsync(IConnectionHandle handle, IReadOnlyList<Dictionary<string, object>> metrics, CancellationToken ct = default){var json = JsonSerializer.Serialize(metrics);var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await handle.GetConnection<HttpClient>().PostAsync("/api/infrastructure-monitoring/metrics", content, ct);response.EnsureSuccessStatusCode();}
    public override Task PushLogsAsync(IConnectionHandle handle, IReadOnlyList<Dictionary<string, object>> logs, CancellationToken ct = default) => throw new NotSupportedException("Instana uses agent-based log collection.");
    public override Task PushTracesAsync(IConnectionHandle handle, IReadOnlyList<Dictionary<string, object>> traces, CancellationToken ct = default) => throw new NotSupportedException("Instana agents handle traces automatically.");
}
