using System;using System.Collections.Generic;using System.Net.Http;using System.Net.Http.Headers;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.Observability;

/// <summary>LogicMonitor connection strategy. HTTPS to *.logicmonitor.com/santaba/rest. SaaS infrastructure monitoring.</summary>
public sealed class LogicMonitorConnectionStrategy : ObservabilityConnectionStrategyBase
{
    public override string StrategyId => "logicmonitor";public override string DisplayName => "LogicMonitor";public override ConnectionStrategyCapabilities Capabilities => new();public override string SemanticDescription => "LogicMonitor SaaS infrastructure monitoring. Auto-discovery, alerting, and hybrid cloud visibility.";public override string[] Tags => ["logicmonitor", "commercial", "infrastructure", "saas", "monitoring"];
    public LogicMonitorConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var baseUrl = config.ConnectionString?.TrimEnd('/') ?? throw new ArgumentException("LogicMonitor portal URL required");var httpClient = new HttpClient { BaseAddress = new Uri(baseUrl), Timeout = config.Timeout };if (config.Properties.TryGetValue("ApiToken", out var token)){httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token.ToString()!);}return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "LogicMonitor", ["BaseUrl"] = baseUrl });}
    protected override async Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct){try { var response = await handle.GetConnection<HttpClient>().GetAsync("/santaba/rest/device/devices", ct); return response.IsSuccessStatusCode; } catch { return false; }}
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override async Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct){var sw = System.Diagnostics.Stopwatch.StartNew();try { var response = await handle.GetConnection<HttpClient>().GetAsync("/santaba/rest/device/devices", ct); sw.Stop(); return new ConnectionHealth(response.IsSuccessStatusCode, "LogicMonitor ready", sw.Elapsed, DateTimeOffset.UtcNow); }catch (Exception ex) { sw.Stop(); return new ConnectionHealth(false, ex.Message, sw.Elapsed, DateTimeOffset.UtcNow); }}
    public override async Task PushMetricsAsync(IConnectionHandle handle, IReadOnlyList<Dictionary<string, object>> metrics, CancellationToken ct = default){var json = JsonSerializer.Serialize(metrics);var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await handle.GetConnection<HttpClient>().PostAsync("/santaba/rest/metric/ingest", content, ct);response.EnsureSuccessStatusCode();}
    public override Task PushLogsAsync(IConnectionHandle handle, IReadOnlyList<Dictionary<string, object>> logs, CancellationToken ct = default) => throw new NotSupportedException("LogicMonitor uses LM Logs module.");
    public override Task PushTracesAsync(IConnectionHandle handle, IReadOnlyList<Dictionary<string, object>> traces, CancellationToken ct = default) => throw new NotSupportedException("LogicMonitor does not support traces.");
}
