using System;using System.Collections.Generic;using System.Net.Http;using System.Runtime.CompilerServices;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.AI;

/// <summary>Anthropic Claude. HTTPS to api.anthropic.com/v1, x-api-key header. Claude 4, Claude 3.5 models.</summary>
public sealed class AnthropicConnectionStrategy : AiConnectionStrategyBase
{
    public override string StrategyId => "anthropic";public override string DisplayName => "Anthropic Claude";public override ConnectionStrategyCapabilities Capabilities => new();public override string SemanticDescription => "Anthropic Claude AI models. Claude 4, Claude 3.5 Sonnet. Constitutional AI with strong reasoning.";public override string[] Tags => ["anthropic", "claude", "llm", "constitutional-ai", "vision"];
    public AnthropicConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var httpClient = new HttpClient { BaseAddress = new Uri("https://api.anthropic.com/v1"), Timeout = config.Timeout };if (config.Properties.TryGetValue("ApiKey", out var apiKey)){httpClient.DefaultRequestHeaders.Add("x-api-key", apiKey.ToString()!);httpClient.DefaultRequestHeaders.Add("anthropic-version", "2023-06-01");}return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "Anthropic" });}
    protected override async Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct){try{var httpClient = handle.GetConnection<HttpClient>();using var response = await httpClient.GetAsync("/", ct);return response.IsSuccessStatusCode;}catch{return false;}}
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override async Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct){var sw = System.Diagnostics.Stopwatch.StartNew();try{var httpClient = handle.GetConnection<HttpClient>();using var response = await httpClient.GetAsync("/", ct);sw.Stop();return new ConnectionHealth(response.IsSuccessStatusCode, response.IsSuccessStatusCode ? "Anthropic connected" : "Anthropic error: HTTP " + (int)response.StatusCode, sw.Elapsed, DateTimeOffset.UtcNow);}catch(Exception ex){sw.Stop();return new ConnectionHealth(false, $"Anthropic error: {ex.Message}", sw.Elapsed, DateTimeOffset.UtcNow);}}
    public override async Task<string> SendRequestAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var payload = new { model = options?.GetValueOrDefault("model", "claude-sonnet-4-20250514") ?? "claude-sonnet-4-20250514", max_tokens = options?.GetValueOrDefault("max_tokens", 4096) ?? 4096, messages = new[] { new { role = "user", content = prompt } } };var json = JsonSerializer.Serialize(payload);using var content = new StringContent(json, Encoding.UTF8, "application/json");using var response = await httpClient.PostAsync("/messages", content, ct);response.EnsureSuccessStatusCode();var result = await response.Content.ReadAsStringAsync(ct);using var doc = JsonDocument.Parse(result);return doc.RootElement.GetProperty("content")[0].GetProperty("text").GetString() ?? "";}
    public override async IAsyncEnumerable<string> StreamResponseAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, [EnumeratorCancellation] CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var payload = new { model = options?.GetValueOrDefault("model", "claude-sonnet-4-20250514") ?? "claude-sonnet-4-20250514", max_tokens = 4096, messages = new[] { new { role = "user", content = prompt } }, stream = true };var json = JsonSerializer.Serialize(payload);using var content = new StringContent(json, Encoding.UTF8, "application/json");using var response = await httpClient.PostAsync("/messages", content, ct);using var stream = await response.Content.ReadAsStreamAsync(ct);using var reader = new System.IO.StreamReader(stream);string? line;while (!ct.IsCancellationRequested && (line = await reader.ReadLineAsync(ct)) != null){if (string.IsNullOrEmpty(line) || !line.StartsWith("data: ")) continue;var data = line.Substring(6);var items = new List<string>();try{using var evt = JsonDocument.Parse(data);if (evt.RootElement.TryGetProperty("delta", out var delta) && delta.TryGetProperty("text", out var text)){items.Add(text.GetString() ?? "");}}catch{continue;}foreach (var item in items) yield return item;}}
}
