using System;using System.Collections.Generic;using System.Net.Http;using System.Runtime.CompilerServices;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.AI;

/// <summary>AWS Bedrock. HTTPS to bedrock-runtime.*.amazonaws.com. Claude, Llama, Titan models on AWS.</summary>
public sealed class AwsBedrockConnectionStrategy : AiConnectionStrategyBase
{
    public override string StrategyId => "aws-bedrock";public override string DisplayName => "AWS Bedrock";public override ConnectionStrategyCapabilities Capabilities => new();public override string SemanticDescription => "AWS Bedrock managed foundation models. Claude, Llama, Titan with AWS integration.";public override string[] Tags => ["aws", "bedrock", "llm", "managed", "multi-model"];
    // Finding 1759: AWS Bedrock requires SigV4 request signing. Raw HttpClient without SigV4 will
    // receive 403 on all model invocations. Mark not production-ready until signing is implemented.
    public override bool IsProductionReady => false;
    public AwsBedrockConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var region = config.Properties.GetValueOrDefault("Region", "us-east-1")?.ToString() ?? "us-east-1";var baseUrl = $"https://bedrock-runtime.{region}.amazonaws.com";var httpClient = new HttpClient { BaseAddress = new Uri(baseUrl), Timeout = config.Timeout };return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "Bedrock", ["Region"] = region });}
    protected override async Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct){try{var httpClient = handle.GetConnection<HttpClient>();using var response = await httpClient.GetAsync("/", ct);return response.IsSuccessStatusCode;}catch{return false;}}
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override async Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct){var sw = System.Diagnostics.Stopwatch.StartNew();try{var httpClient = handle.GetConnection<HttpClient>();using var response = await httpClient.GetAsync("/", ct);sw.Stop();return new ConnectionHealth(response.IsSuccessStatusCode, response.IsSuccessStatusCode ? "AwsBedrock connected" : "AwsBedrock error: HTTP " + (int)response.StatusCode, sw.Elapsed, DateTimeOffset.UtcNow);}catch(Exception ex){sw.Stop();return new ConnectionHealth(false, $"AwsBedrock error: {ex.Message}", sw.Elapsed, DateTimeOffset.UtcNow);}}
    public override async Task<string> SendRequestAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var model = options?.GetValueOrDefault("model", "anthropic.claude-v2") ?? "anthropic.claude-v2";var payload = new { prompt = $"\n\nHuman: {prompt}\n\nAssistant:", max_tokens_to_sample = 2000 };var json = JsonSerializer.Serialize(payload);using var content = new StringContent(json, Encoding.UTF8, "application/json");using var response = await httpClient.PostAsync($"/model/{model}/invoke", content, ct);response.EnsureSuccessStatusCode();var result = await response.Content.ReadAsStringAsync(ct);using var doc = JsonDocument.Parse(result);return doc.RootElement.GetProperty("completion").GetString() ?? "";}
    public override async IAsyncEnumerable<string> StreamResponseAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, [EnumeratorCancellation] CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var model = options?.GetValueOrDefault("model", "anthropic.claude-v2") ?? "anthropic.claude-v2";var payload = new { prompt = $"\n\nHuman: {prompt}\n\nAssistant:", max_tokens_to_sample = 2000 };var json = JsonSerializer.Serialize(payload);using var content = new StringContent(json, Encoding.UTF8, "application/json");using var response = await httpClient.PostAsync($"/model/{model}/invoke-with-response-stream", content, ct);using var stream = await response.Content.ReadAsStreamAsync(ct);using var reader = new System.IO.StreamReader(stream);string? line;while (!ct.IsCancellationRequested && (line = await reader.ReadLineAsync(ct)) != null){if (string.IsNullOrEmpty(line)) continue;var items = new List<string>();try{using var evt = JsonDocument.Parse(line);if (evt.RootElement.TryGetProperty("completion", out var comp)){items.Add(comp.GetString() ?? "");}}catch{continue;}foreach (var item in items) yield return item;}}
}
