using System;using System.Collections.Generic;using System.Net.Http;using System.Runtime.CompilerServices;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.AI;

/// <summary>AWS Bedrock. HTTPS to bedrock-runtime.*.amazonaws.com. Claude, Llama, Titan models on AWS.</summary>
public sealed class AwsBedrockConnectionStrategy : AiConnectionStrategyBase
{
    public override string StrategyId => "aws-bedrock";public override string DisplayName => "AWS Bedrock";public override ConnectionStrategyCapabilities Capabilities => new();public override string SemanticDescription => "AWS Bedrock managed foundation models. Claude, Llama, Titan with AWS integration.";public override string[] Tags => ["aws", "bedrock", "llm", "managed", "multi-model"];
    public AwsBedrockConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var region = config.Properties.GetValueOrDefault("Region", "us-east-1")?.ToString() ?? "us-east-1";var baseUrl = $"https://bedrock-runtime.{region}.amazonaws.com";var httpClient = new HttpClient { BaseAddress = new Uri(baseUrl), Timeout = config.Timeout };return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "Bedrock", ["Region"] = region });}
    protected override Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct) => Task.FromResult(true);
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct) => Task.FromResult(new ConnectionHealth(true, "Bedrock configured", TimeSpan.Zero, DateTimeOffset.UtcNow));
    public override async Task<string> SendRequestAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var model = options?.GetValueOrDefault("model", "anthropic.claude-v2") ?? "anthropic.claude-v2";var payload = new { prompt = $"\n\nHuman: {prompt}\n\nAssistant:", max_tokens_to_sample = 2000 };var json = JsonSerializer.Serialize(payload);var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync($"/model/{model}/invoke", content, ct);response.EnsureSuccessStatusCode();var result = await response.Content.ReadAsStringAsync(ct);var doc = JsonDocument.Parse(result);return doc.RootElement.GetProperty("completion").GetString() ?? "";}
    public override async IAsyncEnumerable<string> StreamResponseAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, [EnumeratorCancellation] CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var model = options?.GetValueOrDefault("model", "anthropic.claude-v2") ?? "anthropic.claude-v2";var payload = new { prompt = $"\n\nHuman: {prompt}\n\nAssistant:", max_tokens_to_sample = 2000 };var json = JsonSerializer.Serialize(payload);var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync($"/model/{model}/invoke-with-response-stream", content, HttpCompletionOption.ResponseHeadersRead, ct);using var stream = await response.Content.ReadAsStreamAsync(ct);using var reader = new System.IO.StreamReader(stream);while (!reader.EndOfStream && !ct.IsCancellationRequested){var line = await reader.ReadLineAsync(ct);if (string.IsNullOrEmpty(line)) continue;try{var evt = JsonDocument.Parse(line);if (evt.RootElement.TryGetProperty("completion", out var comp)){yield return comp.GetString() ?? "";}}catch{continue;}}}
}
