using System;using System.Collections.Generic;using System.Net.Http;using System.Runtime.CompilerServices;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.AI;

/// <summary>AWS SageMaker. HTTPS to runtime.sagemaker.*.amazonaws.com. Model deployment, real-time inference endpoints.</summary>
public sealed class AwsSageMakerConnectionStrategy : AiConnectionStrategyBase
{
    public override string StrategyId => "ai-sagemaker";public override string DisplayName => "AWS SageMaker";public override ConnectionStrategyCapabilities Capabilities => new(SupportsPooling: false, SupportsStreaming: true, SupportsAuthentication: true);public override string SemanticDescription => "AWS SageMaker managed ML platform. Real-time inference endpoints, batch transforms, and model deployment.";public override string[] Tags => ["aws", "sagemaker", "ml-platform", "inference", "model-deployment"];
    public AwsSageMakerConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var region = config.Properties.GetValueOrDefault("Region", "us-east-1")?.ToString() ?? "us-east-1";var baseUrl = $"https://runtime.sagemaker.{region}.amazonaws.com";var httpClient = new HttpClient { BaseAddress = new Uri(baseUrl), Timeout = config.Timeout };return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "SageMaker", ["Region"] = region });}
    protected override Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct) => Task.FromResult(true);
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct) => Task.FromResult(new ConnectionHealth(true, "SageMaker configured", TimeSpan.Zero, DateTimeOffset.UtcNow));
    public override async Task<string> SendRequestAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var endpointName = options?.GetValueOrDefault("endpoint", "")?.ToString() ?? throw new ArgumentException("SageMaker endpoint name required in options");var contentType = options?.GetValueOrDefault("content_type", "application/json")?.ToString() ?? "application/json";var content = new StringContent(prompt, Encoding.UTF8, contentType);var response = await httpClient.PostAsync($"/endpoints/{endpointName}/invocations", content, ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}
    public override async IAsyncEnumerable<string> StreamResponseAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, [EnumeratorCancellation] CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var endpointName = options?.GetValueOrDefault("endpoint", "")?.ToString() ?? throw new ArgumentException("SageMaker endpoint name required in options");var content = new StringContent(prompt, Encoding.UTF8, "application/json");var request = new HttpRequestMessage(HttpMethod.Post, $"/endpoints/{endpointName}/invocations-response-stream"){Content = content};var response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, ct);using var stream = await response.Content.ReadAsStreamAsync(ct);using var reader = new System.IO.StreamReader(stream);while (!reader.EndOfStream && !ct.IsCancellationRequested){var line = await reader.ReadLineAsync(ct);if (string.IsNullOrEmpty(line)) continue;string? chunk = null;try{var evt = JsonDocument.Parse(line);if (evt.RootElement.TryGetProperty("PayloadPart", out var payload) && payload.TryGetProperty("Bytes", out var bytes)){chunk = bytes.GetString();}}catch{chunk = line;}if (chunk != null) yield return chunk;}}
}
