using System;using System.Collections.Generic;using System.Net.Http;using System.Net.Http.Headers;using System.Runtime.CompilerServices;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.AI;

/// <summary>Azure Machine Learning. HTTPS to *.api.azureml.ms. Workspace management, experiments, online endpoints.</summary>
public sealed class AzureMlConnectionStrategy : AiConnectionStrategyBase
{
    public override string StrategyId => "ai-azure-ml";public override string DisplayName => "Azure Machine Learning";public override ConnectionStrategyCapabilities Capabilities => new(SupportsPooling: false, SupportsStreaming: true, SupportsAuthentication: true);public override string SemanticDescription => "Azure Machine Learning managed ML platform. Workspace management, experiments, pipelines, and online/batch endpoints.";public override string[] Tags => ["azure", "azure-ml", "ml-platform", "workspace", "endpoints", "pipelines"];
    public AzureMlConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var scoringUri = config.ConnectionString ?? throw new ArgumentException("Azure ML scoring endpoint URI required");var httpClient = new HttpClient { BaseAddress = new Uri(scoringUri), Timeout = config.Timeout };if (config.Properties.TryGetValue("ApiKey", out var apiKey)){httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", apiKey.ToString()!);}else if (config.Properties.TryGetValue("AccessToken", out var token)){httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token.ToString()!);}return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "AzureML", ["ScoringUri"] = scoringUri });}
    protected override Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct) => Task.FromResult(true);
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct) => Task.FromResult(new ConnectionHealth(true, "Azure ML configured", TimeSpan.Zero, DateTimeOffset.UtcNow));
    public override async Task<string> SendRequestAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var payload = options?.GetValueOrDefault("payload", null);var json = payload != null ? JsonSerializer.Serialize(payload) : JsonSerializer.Serialize(new { input_data = new { input_string = new[] { prompt } } });var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync("/score", content, ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}
    public override async IAsyncEnumerable<string> StreamResponseAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, [EnumeratorCancellation] CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var json = JsonSerializer.Serialize(new { input_data = new { input_string = new[] { prompt } }, stream = true });var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync("/score", content, HttpCompletionOption.ResponseHeadersRead, ct);using var stream = await response.Content.ReadAsStreamAsync(ct);using var reader = new System.IO.StreamReader(stream);while (!reader.EndOfStream && !ct.IsCancellationRequested){var line = await reader.ReadLineAsync(ct);if (string.IsNullOrEmpty(line)) continue;try{var evt = JsonDocument.Parse(line);if (evt.RootElement.TryGetProperty("content", out var contentProp)){yield return contentProp.GetString() ?? "";}else{yield return line;}}catch{yield return line;}}}
}
