using System;using System.Collections.Generic;using System.Net.Http;using System.Runtime.CompilerServices;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.AI;

/// <summary>Azure OpenAI. HTTPS to *.openai.azure.com, api-key header. Enterprise OpenAI with Azure integration.</summary>
public sealed class AzureOpenAiConnectionStrategy : AiConnectionStrategyBase
{
    public override string StrategyId => "azure-openai";public override string DisplayName => "Azure OpenAI";public override ConnectionStrategyCapabilities Capabilities => new();public override string SemanticDescription => "Azure OpenAI Service. Enterprise GPT-4 with Azure security, compliance, and private deployment.";public override string[] Tags => ["azure", "openai", "llm", "enterprise", "microsoft"];
    public AzureOpenAiConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var baseUrl = config.ConnectionString?.TrimEnd('/') ?? throw new ArgumentException("Azure OpenAI endpoint required");var httpClient = new HttpClient { BaseAddress = new Uri(baseUrl), Timeout = config.Timeout };if (config.Properties.TryGetValue("ApiKey", out var apiKey)){httpClient.DefaultRequestHeaders.Add("api-key", apiKey.ToString()!);}return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "AzureOpenAI", ["BaseUrl"] = baseUrl });}
    protected override async Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct){try{var httpClient = handle.GetConnection<HttpClient>();using var response = await httpClient.GetAsync("/", ct);return response.IsSuccessStatusCode;}catch{return false;}}
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override async Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct){var sw = System.Diagnostics.Stopwatch.StartNew();try{var httpClient = handle.GetConnection<HttpClient>();using var response = await httpClient.GetAsync("/", ct);sw.Stop();return new ConnectionHealth(response.IsSuccessStatusCode, response.IsSuccessStatusCode ? "AzureOpenAi connected" : "AzureOpenAi error: HTTP " + (int)response.StatusCode, sw.Elapsed, DateTimeOffset.UtcNow);}catch(Exception ex){sw.Stop();return new ConnectionHealth(false, $"AzureOpenAi error: {ex.Message}", sw.Elapsed, DateTimeOffset.UtcNow);}}
    public override async Task<string> SendRequestAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var deployment = options?.GetValueOrDefault("deployment", "gpt-4o") ?? "gpt-4o";var payload = new { messages = new[] { new { role = "user", content = prompt } }, temperature = options?.GetValueOrDefault("temperature", 0.7) };var json = JsonSerializer.Serialize(payload);using var content = new StringContent(json, Encoding.UTF8, "application/json");using var response = await httpClient.PostAsync($"/openai/deployments/{deployment}/chat/completions?api-version=2024-02-01", content, ct);response.EnsureSuccessStatusCode();var result = await response.Content.ReadAsStringAsync(ct);using var doc = JsonDocument.Parse(result);return doc.RootElement.GetProperty("choices")[0].GetProperty("message").GetProperty("content").GetString() ?? "";}
    public override async IAsyncEnumerable<string> StreamResponseAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, [EnumeratorCancellation] CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var deployment = options?.GetValueOrDefault("deployment", "gpt-4o") ?? "gpt-4o";var payload = new { messages = new[] { new { role = "user", content = prompt } }, stream = true };var json = JsonSerializer.Serialize(payload);using var content = new StringContent(json, Encoding.UTF8, "application/json");using var response = await httpClient.PostAsync($"/openai/deployments/{deployment}/chat/completions?api-version=2024-02-01", content, ct);using var stream = await response.Content.ReadAsStreamAsync(ct);using var reader = new System.IO.StreamReader(stream);string? line;while (!ct.IsCancellationRequested && (line = await reader.ReadLineAsync(ct)) != null){if (string.IsNullOrEmpty(line) || !line.StartsWith("data: ")) continue;var data = line.Substring(6);if (data == "[DONE]") break;var items = new List<string>();try{using var evt = JsonDocument.Parse(data);var delta = evt.RootElement.GetProperty("choices")[0].GetProperty("delta");if (delta.TryGetProperty("content", out var contentProp)){items.Add(contentProp.GetString() ?? "");}}catch{continue;}foreach (var item in items) yield return item;}}
}
