using System;using System.Collections.Generic;using System.Net.Http;using System.Runtime.CompilerServices;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.AI;

/// <summary>ChromaDB vector database. REST API. Collection management, embedding storage and retrieval.</summary>
public sealed class ChromaConnectionStrategy : AiConnectionStrategyBase
{
    public override string StrategyId => "ai-chroma";public override string DisplayName => "ChromaDB";public override ConnectionStrategyCapabilities Capabilities => new(SupportsPooling: false, SupportsStreaming: false, SupportsAuthentication: false);public override string SemanticDescription => "ChromaDB open-source embedding database. Simple API for collection management, embedding storage and similarity search.";public override string[] Tags => ["chroma", "chromadb", "vector-db", "embeddings", "open-source"];
    public ChromaConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var baseUrl = config.ConnectionString ?? "http://localhost:8000";var httpClient = new HttpClient { BaseAddress = new Uri(baseUrl), Timeout = config.Timeout };if (config.Properties.TryGetValue("ApiKey", out var apiKey)){httpClient.DefaultRequestHeaders.Add("X-Chroma-Token", apiKey.ToString()!);}return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "Chroma", ["BaseUrl"] = baseUrl });}
    protected override async Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct){var httpClient = handle.GetConnection<HttpClient>();var response = await httpClient.GetAsync("/api/v1/heartbeat", ct);return response.IsSuccessStatusCode;}
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override async Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct){var httpClient = handle.GetConnection<HttpClient>();try{var response = await httpClient.GetAsync("/api/v1/heartbeat", ct);return new ConnectionHealth(response.IsSuccessStatusCode, response.IsSuccessStatusCode ? "ChromaDB running" : "ChromaDB unreachable", TimeSpan.Zero, DateTimeOffset.UtcNow);}catch (Exception ex){return new ConnectionHealth(false, $"ChromaDB error: {ex.Message}", TimeSpan.Zero, DateTimeOffset.UtcNow);}}
    public override async Task<string> SendRequestAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var action = options?.GetValueOrDefault("action", "query")?.ToString() ?? "query";var collection = options?.GetValueOrDefault("collection", "default")?.ToString() ?? "default";if (action == "add"){var ids = options?.GetValueOrDefault("ids", null);var embeddings = options?.GetValueOrDefault("embeddings", null);var documents = options?.GetValueOrDefault("documents", null);var metadatas = options?.GetValueOrDefault("metadatas", null);var json = JsonSerializer.Serialize(new { ids, embeddings, documents, metadatas });var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync($"/api/v1/collections/{collection}/add", content, ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}else if (action == "query"){var queryEmbeddings = options?.GetValueOrDefault("query_embeddings", null);var nResults = options?.GetValueOrDefault("n_results", 10) ?? 10;var json = JsonSerializer.Serialize(new { query_embeddings = queryEmbeddings, n_results = nResults });var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync($"/api/v1/collections/{collection}/query", content, ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}else{var response = await httpClient.GetAsync("/api/v1/collections", ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}}
    public override async IAsyncEnumerable<string> StreamResponseAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, [EnumeratorCancellation] CancellationToken ct = default){throw new NotSupportedException("ChromaDB does not support streaming responses. Use SendRequestAsync for vector operations.");yield break;}
}
