using System;using System.Collections.Generic;using System.Net.Http;using System.Net.Http.Headers;using System.Runtime.CompilerServices;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.AI;

/// <summary>Deepgram speech-to-text. HTTPS to api.deepgram.com/v1. Real-time and batch transcription with diarization.</summary>
public sealed class DeepgramConnectionStrategy : AiConnectionStrategyBase
{
    public override string StrategyId => "ai-deepgram";public override string DisplayName => "Deepgram";public override ConnectionStrategyCapabilities Capabilities => new(SupportsPooling: false, SupportsStreaming: true, SupportsAuthentication: true);public override string SemanticDescription => "Deepgram AI speech-to-text platform. Real-time and batch transcription with speaker diarization, language detection, and summarization.";public override string[] Tags => ["deepgram", "stt", "speech-to-text", "transcription", "diarization"];
    public DeepgramConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var httpClient = new HttpClient { BaseAddress = new Uri("https://api.deepgram.com/v1"), Timeout = config.Timeout };if (config.Properties.TryGetValue("ApiKey", out var apiKey)){httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Token", apiKey.ToString()!);}return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "Deepgram" });}
    protected override async Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct){var httpClient = handle.GetConnection<HttpClient>();using var response = await httpClient.GetAsync("/projects", ct);return response.IsSuccessStatusCode;}
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override async Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct){var httpClient = handle.GetConnection<HttpClient>();try{using var response = await httpClient.GetAsync("/projects", ct);return new ConnectionHealth(response.IsSuccessStatusCode, response.IsSuccessStatusCode ? "Deepgram connected" : "Deepgram unreachable", TimeSpan.Zero, DateTimeOffset.UtcNow);}catch (Exception ex){return new ConnectionHealth(false, $"Deepgram error: {ex.Message}", TimeSpan.Zero, DateTimeOffset.UtcNow);}}
    public override async Task<string> SendRequestAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var action = options?.GetValueOrDefault("action", "transcribe_url")?.ToString() ?? "transcribe_url";var model = options?.GetValueOrDefault("model", "nova-2")?.ToString() ?? "nova-2";if (action == "transcribe_url"){var json = JsonSerializer.Serialize(new { url = prompt });using var content = new StringContent(json, Encoding.UTF8, "application/json");using var response = await httpClient.PostAsync($"/listen?model={model}&smart_format=true", content, ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}else if (action == "transcribe_audio"){var audioBytes = Convert.FromBase64String(prompt);var content = new ByteArrayContent(audioBytes);content.Headers.ContentType = new MediaTypeHeaderValue("audio/wav");using var response = await httpClient.PostAsync($"/listen?model={model}&smart_format=true", content, ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}else{using var response = await httpClient.GetAsync("/projects", ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}}
    public override async IAsyncEnumerable<string> StreamResponseAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, [EnumeratorCancellation] CancellationToken ct = default){ThrowStreamingNotSupported("Deepgram real-time streaming requires WebSocket connection. Use SendRequestAsync for batch transcription or establish a WebSocket for live streaming.");yield break;}
}
