using System;using System.Collections.Generic;using System.Net.Http;using System.Net.Http.Headers;using System.Runtime.CompilerServices;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.AI;

/// <summary>ElevenLabs TTS/Voice API. HTTPS to api.elevenlabs.io/v1. Voice cloning, speech synthesis, voice design.</summary>
public sealed class ElevenLabsConnectionStrategy : AiConnectionStrategyBase
{
    public override string StrategyId => "ai-elevenlabs";public override string DisplayName => "ElevenLabs";public override ConnectionStrategyCapabilities Capabilities => new(SupportsPooling: false, SupportsStreaming: true, SupportsAuthentication: true);public override string SemanticDescription => "ElevenLabs AI voice platform. Text-to-speech synthesis, voice cloning, voice design, and multilingual speech generation.";public override string[] Tags => ["elevenlabs", "tts", "voice", "speech-synthesis", "voice-cloning"];
    public ElevenLabsConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var httpClient = new HttpClient { BaseAddress = new Uri("https://api.elevenlabs.io/v1"), Timeout = config.Timeout };if (config.Properties.TryGetValue("ApiKey", out var apiKey)){httpClient.DefaultRequestHeaders.Add("xi-api-key", apiKey.ToString()!);}return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "ElevenLabs" });}
    protected override async Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct){var httpClient = handle.GetConnection<HttpClient>();using var response = await httpClient.GetAsync("/voices", ct);return response.IsSuccessStatusCode;}
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override async Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct){var httpClient = handle.GetConnection<HttpClient>();try{using var response = await httpClient.GetAsync("/voices", ct);return new ConnectionHealth(response.IsSuccessStatusCode, response.IsSuccessStatusCode ? "ElevenLabs connected" : "ElevenLabs unreachable", TimeSpan.Zero, DateTimeOffset.UtcNow);}catch (Exception ex){return new ConnectionHealth(false, $"ElevenLabs error: {ex.Message}", TimeSpan.Zero, DateTimeOffset.UtcNow);}}
    public override async Task<string> SendRequestAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var action = options?.GetValueOrDefault("action", "tts")?.ToString() ?? "tts";if (action == "tts"){var voiceId = options?.GetValueOrDefault("voice_id", "21m00Tcm4TlvDq8ikWAM")?.ToString() ?? "21m00Tcm4TlvDq8ikWAM";var modelId = options?.GetValueOrDefault("model_id", "eleven_monolingual_v1")?.ToString() ?? "eleven_monolingual_v1";var payload = new { text = prompt, model_id = modelId, voice_settings = new { stability = 0.5, similarity_boost = 0.75 } };var json = JsonSerializer.Serialize(payload);using var content = new StringContent(json, Encoding.UTF8, "application/json");using var response = await httpClient.PostAsync($"/text-to-speech/{Uri.EscapeDataString(voiceId)}", content, ct);response.EnsureSuccessStatusCode();var audioBytes = await response.Content.ReadAsByteArrayAsync(ct);return Convert.ToBase64String(audioBytes);}else if (action == "voices"){using var response = await httpClient.GetAsync("/voices", ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}else{using var response = await httpClient.GetAsync("/models", ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}}
    public override async IAsyncEnumerable<string> StreamResponseAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, [EnumeratorCancellation] CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var voiceId = options?.GetValueOrDefault("voice_id", "21m00Tcm4TlvDq8ikWAM")?.ToString() ?? "21m00Tcm4TlvDq8ikWAM";var payload = new { text = prompt, model_id = "eleven_monolingual_v1", voice_settings = new { stability = 0.5, similarity_boost = 0.75 } };var json = JsonSerializer.Serialize(payload);using var content = new StringContent(json, Encoding.UTF8, "application/json");var request = new HttpRequestMessage(HttpMethod.Post, $"/text-to-speech/{Uri.EscapeDataString(voiceId)}/stream"){Content = content};using var response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, ct);using var stream = await response.Content.ReadAsStreamAsync(ct);var buffer = new byte[4096];int bytesRead;while ((bytesRead = await stream.ReadAsync(buffer, 0, buffer.Length, ct)) > 0 && !ct.IsCancellationRequested){yield return Convert.ToBase64String(buffer, 0, bytesRead);}}
}
