using System;using System.Collections.Generic;using System.Net.Http;using System.Runtime.CompilerServices;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.AI;

/// <summary>Google Gemini. HTTPS to generativelanguage.googleapis.com. Gemini Pro, Ultra models.</summary>
public sealed class GoogleGeminiConnectionStrategy : AiConnectionStrategyBase
{
    public override string StrategyId => "google-gemini";public override string DisplayName => "Google Gemini";public override ConnectionStrategyCapabilities Capabilities => new();public override string SemanticDescription => "Google Gemini AI models. Multimodal capabilities with vision and long context windows.";public override string[] Tags => ["google", "gemini", "llm", "multimodal", "vision"];
    public GoogleGeminiConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var httpClient = new HttpClient { BaseAddress = new Uri("https://generativelanguage.googleapis.com"), Timeout = config.Timeout };return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "Gemini", ["ApiKey"] = config.Properties.GetValueOrDefault("ApiKey", "") });}
    protected override Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct) => Task.FromResult(true);
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct) => Task.FromResult(new ConnectionHealth(true, "Gemini configured", TimeSpan.Zero, DateTimeOffset.UtcNow));
    public override async Task<string> SendRequestAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var apiKey = handle.ConnectionInfo["ApiKey"]?.ToString();var model = options?.GetValueOrDefault("model", "gemini-pro") ?? "gemini-pro";var payload = new { contents = new[] { new { parts = new[] { new { text = prompt } } } } };var json = JsonSerializer.Serialize(payload);var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync($"/v1/models/{model}:generateContent?key={apiKey}", content, ct);response.EnsureSuccessStatusCode();var result = await response.Content.ReadAsStringAsync(ct);var doc = JsonDocument.Parse(result);return doc.RootElement.GetProperty("candidates")[0].GetProperty("content").GetProperty("parts")[0].GetProperty("text").GetString() ?? "";}
    public override async IAsyncEnumerable<string> StreamResponseAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, [EnumeratorCancellation] CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var apiKey = handle.ConnectionInfo["ApiKey"]?.ToString();var model = options?.GetValueOrDefault("model", "gemini-pro") ?? "gemini-pro";var payload = new { contents = new[] { new { parts = new[] { new { text = prompt } } } } };var json = JsonSerializer.Serialize(payload);var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync($"/v1/models/{model}:streamGenerateContent?key={apiKey}", content, HttpCompletionOption.ResponseHeadersRead, ct);using var stream = await response.Content.ReadAsStreamAsync(ct);using var reader = new System.IO.StreamReader(stream);while (!reader.EndOfStream && !ct.IsCancellationRequested){var line = await reader.ReadLineAsync(ct);if (string.IsNullOrEmpty(line)) continue;try{var evt = JsonDocument.Parse(line);if (evt.RootElement.TryGetProperty("candidates", out var candidates) && candidates.GetArrayLength() > 0){var text = candidates[0].GetProperty("content").GetProperty("parts")[0].GetProperty("text").GetString();if (text != null) yield return text;}}catch{continue;}}}
}
