using System;using System.Collections.Generic;using System.Net.Http;using System.Runtime.CompilerServices;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.AI;

/// <summary>Google Gemini. HTTPS to generativelanguage.googleapis.com. Gemini Pro, Ultra models.</summary>
public sealed class GoogleGeminiConnectionStrategy : AiConnectionStrategyBase
{
    public override string StrategyId => "google-gemini";public override string DisplayName => "Google Gemini";public override ConnectionStrategyCapabilities Capabilities => new();public override string SemanticDescription => "Google Gemini AI models. Multimodal capabilities with vision and long context windows.";public override string[] Tags => ["google", "gemini", "llm", "multimodal", "vision"];
    public GoogleGeminiConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var httpClient = new HttpClient { BaseAddress = new Uri("https://generativelanguage.googleapis.com"), Timeout = config.Timeout };var apiKey = config.Properties.GetValueOrDefault("ApiKey", "")?.ToString() ?? "";if (!string.IsNullOrEmpty(apiKey)){httpClient.DefaultRequestHeaders.Add("x-goog-api-key", apiKey);}return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "Gemini", ["ApiKey"] = apiKey });}
    protected override async Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct){try{var httpClient = handle.GetConnection<HttpClient>();using var response = await httpClient.GetAsync("/", ct);return response.IsSuccessStatusCode;}catch{return false;}}
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override async Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct){var sw = System.Diagnostics.Stopwatch.StartNew();try{var httpClient = handle.GetConnection<HttpClient>();using var response = await httpClient.GetAsync("/", ct);sw.Stop();return new ConnectionHealth(response.IsSuccessStatusCode, response.IsSuccessStatusCode ? "GoogleGemini connected" : "GoogleGemini error: HTTP " + (int)response.StatusCode, sw.Elapsed, DateTimeOffset.UtcNow);}catch(Exception ex){sw.Stop();return new ConnectionHealth(false, $"GoogleGemini error: {ex.Message}", sw.Elapsed, DateTimeOffset.UtcNow);}}
    public override async Task<string> SendRequestAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var model = options?.GetValueOrDefault("model", "gemini-pro") ?? "gemini-pro";var payload = new { contents = new[] { new { parts = new[] { new { text = prompt } } } } };var json = JsonSerializer.Serialize(payload);using var content = new StringContent(json, Encoding.UTF8, "application/json");using var response = await httpClient.PostAsync($"/v1/models/{model}:generateContent", content, ct);response.EnsureSuccessStatusCode();var result = await response.Content.ReadAsStringAsync(ct);using var doc = JsonDocument.Parse(result);return doc.RootElement.GetProperty("candidates")[0].GetProperty("content").GetProperty("parts")[0].GetProperty("text").GetString() ?? "";}
    public override async IAsyncEnumerable<string> StreamResponseAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, [EnumeratorCancellation] CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var model = options?.GetValueOrDefault("model", "gemini-pro") ?? "gemini-pro";var payload = new { contents = new[] { new { parts = new[] { new { text = prompt } } } } };var json = JsonSerializer.Serialize(payload);using var content = new StringContent(json, Encoding.UTF8, "application/json");using var response = await httpClient.PostAsync($"/v1/models/{model}:streamGenerateContent", content, ct);using var stream = await response.Content.ReadAsStreamAsync(ct);using var reader = new System.IO.StreamReader(stream);string? line;while (!ct.IsCancellationRequested && (line = await reader.ReadLineAsync(ct)) != null){if (string.IsNullOrEmpty(line)) continue;var items = new List<string>();try{using var evt = JsonDocument.Parse(line);if (evt.RootElement.TryGetProperty("candidates", out var candidates) && candidates.GetArrayLength() > 0){var text = candidates[0].GetProperty("content").GetProperty("parts")[0].GetProperty("text").GetString();if (text != null) items.Add(text);}}catch{continue;}foreach (var item in items) yield return item;}}
}
