using System;using System.Collections.Generic;using System.Net.Http;using System.Net.Http.Headers;using System.Runtime.CompilerServices;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.AI;

/// <summary>Groq. HTTPS to api.groq.com/openai/v1. Ultra-fast LLM inference with LPU.</summary>
public sealed class GroqConnectionStrategy : AiConnectionStrategyBase
{
    public override string StrategyId => "groq";public override string DisplayName => "Groq";public override ConnectionStrategyCapabilities Capabilities => new();public override string SemanticDescription => "Groq ultra-fast LLM inference using Language Processing Units (LPUs). Sub-second response times.";public override string[] Tags => ["groq", "llm", "lpu", "ultra-fast", "inference"];
    public GroqConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var httpClient = new HttpClient { BaseAddress = new Uri("https://api.groq.com/openai/v1"), Timeout = config.Timeout };if (config.Properties.TryGetValue("ApiKey", out var apiKey)){httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", apiKey.ToString()!);}return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "Groq" });}
    protected override Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct) => Task.FromResult(true);
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct) => Task.FromResult(new ConnectionHealth(true, "Groq configured", TimeSpan.Zero, DateTimeOffset.UtcNow));
    public override async Task<string> SendRequestAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var model = options?.GetValueOrDefault("model", "llama3-70b-8192") ?? "llama3-70b-8192";var payload = new { model, messages = new[] { new { role = "user", content = prompt } } };var json = JsonSerializer.Serialize(payload);var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync("/chat/completions", content, ct);response.EnsureSuccessStatusCode();var result = await response.Content.ReadAsStringAsync(ct);var doc = JsonDocument.Parse(result);return doc.RootElement.GetProperty("choices")[0].GetProperty("message").GetProperty("content").GetString() ?? "";}
    public override async IAsyncEnumerable<string> StreamResponseAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, [EnumeratorCancellation] CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var model = options?.GetValueOrDefault("model", "llama3-70b-8192") ?? "llama3-70b-8192";var payload = new { model, messages = new[] { new { role = "user", content = prompt } }, stream = true };var json = JsonSerializer.Serialize(payload);var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync("/chat/completions", content);using var stream = await response.Content.ReadAsStreamAsync(ct);using var reader = new System.IO.StreamReader(stream);string? line;while (!ct.IsCancellationRequested && (line = await reader.ReadLineAsync(ct)) != null){if (string.IsNullOrEmpty(line) || !line.StartsWith("data: ")) continue;var data = line.Substring(6);if (data == "[DONE]") break;var items = new List<string>();try{var evt = JsonDocument.Parse(data);var delta = evt.RootElement.GetProperty("choices")[0].GetProperty("delta");if (delta.TryGetProperty("content", out var contentProp)){items.Add(contentProp.GetString() ?? "");}}catch{continue;}foreach (var item in items) yield return item;}}
}
