using System;using System.Collections.Generic;using System.Net.Http;using System.Net.Http.Headers;using System.Runtime.CompilerServices;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.AI;

/// <summary>HuggingFace Inference API. HTTPS to api-inference.huggingface.co. Thousands of open-source models.</summary>
public sealed class HuggingFaceConnectionStrategy : AiConnectionStrategyBase
{
    public override string StrategyId => "ai-huggingface";public override string DisplayName => "HuggingFace Inference";public override ConnectionStrategyCapabilities Capabilities => new(SupportsPooling: false, SupportsStreaming: true, SupportsAuthentication: true);public override string SemanticDescription => "HuggingFace Inference API. Access thousands of open-source models for text generation, embeddings, and more.";public override string[] Tags => ["huggingface", "llm", "inference", "open-source", "embeddings", "transformers"];
    public HuggingFaceConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var httpClient = new HttpClient { BaseAddress = new Uri("https://api-inference.huggingface.co"), Timeout = config.Timeout };if (config.Properties.TryGetValue("ApiKey", out var apiKey)){httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", apiKey.ToString()!);}return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "HuggingFace" });}
    protected override async Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct){try{var httpClient = handle.GetConnection<HttpClient>();using var response = await httpClient.GetAsync("/", ct);return response.IsSuccessStatusCode;}catch{return false;}}
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override async Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct){var sw = System.Diagnostics.Stopwatch.StartNew();try{var httpClient = handle.GetConnection<HttpClient>();using var response = await httpClient.GetAsync("/", ct);sw.Stop();return new ConnectionHealth(response.IsSuccessStatusCode, response.IsSuccessStatusCode ? "HuggingFace connected" : "HuggingFace error: HTTP " + (int)response.StatusCode, sw.Elapsed, DateTimeOffset.UtcNow);}catch(Exception ex){sw.Stop();return new ConnectionHealth(false, $"HuggingFace error: {ex.Message}", sw.Elapsed, DateTimeOffset.UtcNow);}}
    public override async Task<string> SendRequestAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var model = options?.GetValueOrDefault("model", "meta-llama/Meta-Llama-3-8B-Instruct") ?? "meta-llama/Meta-Llama-3-8B-Instruct";var payload = new { inputs = prompt, parameters = new { max_new_tokens = options?.GetValueOrDefault("max_tokens", 512) ?? 512, temperature = options?.GetValueOrDefault("temperature", 0.7) } };var json = JsonSerializer.Serialize(payload);using var content = new StringContent(json, Encoding.UTF8, "application/json");using var response = await httpClient.PostAsync($"/models/{model}", content, ct);response.EnsureSuccessStatusCode();var result = await response.Content.ReadAsStringAsync(ct);using var doc = JsonDocument.Parse(result);if (doc.RootElement.ValueKind == JsonValueKind.Array && doc.RootElement.GetArrayLength() > 0){return doc.RootElement[0].GetProperty("generated_text").GetString() ?? "";}return doc.RootElement.GetProperty("generated_text").GetString() ?? "";}
    public override async IAsyncEnumerable<string> StreamResponseAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, [EnumeratorCancellation] CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var model = options?.GetValueOrDefault("model", "meta-llama/Meta-Llama-3-8B-Instruct") ?? "meta-llama/Meta-Llama-3-8B-Instruct";var payload = new { inputs = prompt, parameters = new { max_new_tokens = 512 }, stream = true };var json = JsonSerializer.Serialize(payload);using var content = new StringContent(json, Encoding.UTF8, "application/json");var request = new HttpRequestMessage(HttpMethod.Post, $"/models/{model}"){Content = content};using var response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, ct);using var stream = await response.Content.ReadAsStreamAsync(ct);using var reader = new System.IO.StreamReader(stream);string? line;while (!ct.IsCancellationRequested && (line = await reader.ReadLineAsync(ct)) != null){if (string.IsNullOrEmpty(line) || !line.StartsWith("data:")) continue;var data = line.StartsWith("data: ") ? line.Substring(6) : line.Substring(5);string? chunk = null;try{using var evt = JsonDocument.Parse(data);if (evt.RootElement.TryGetProperty("token", out var token) && token.TryGetProperty("text", out var text)){chunk = text.GetString();}}catch{/* skip malformed */}if (chunk != null) yield return chunk;}}
}
