using System;using System.Collections.Generic;using System.Net.Http;using System.Net.Http.Headers;using System.Runtime.CompilerServices;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.AI;

/// <summary>LangSmith tracing API. HTTPS to api.smith.langchain.com. LLM observability, evaluation runs, dataset management.</summary>
public sealed class LangSmithConnectionStrategy : AiConnectionStrategyBase
{
    public override string StrategyId => "ai-langsmith";public override string DisplayName => "LangSmith";public override ConnectionStrategyCapabilities Capabilities => new(SupportsPooling: false, SupportsStreaming: false, SupportsAuthentication: true);public override string SemanticDescription => "LangSmith LLM observability and evaluation platform. Trace logging, evaluation runs, dataset management, and prompt engineering.";public override string[] Tags => ["langsmith", "langchain", "llm-observability", "tracing", "evaluation"];
    public LangSmithConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var baseUrl = config.ConnectionString ?? "https://api.smith.langchain.com";var httpClient = new HttpClient { BaseAddress = new Uri(baseUrl), Timeout = config.Timeout };if (config.Properties.TryGetValue("ApiKey", out var apiKey)){httpClient.DefaultRequestHeaders.Add("x-api-key", apiKey.ToString()!);}return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "LangSmith", ["BaseUrl"] = baseUrl });}
    protected override async Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct){var httpClient = handle.GetConnection<HttpClient>();var response = await httpClient.GetAsync("/api/v1/info", ct);return response.IsSuccessStatusCode;}
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override async Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct){var httpClient = handle.GetConnection<HttpClient>();try{var response = await httpClient.GetAsync("/api/v1/info", ct);return new ConnectionHealth(response.IsSuccessStatusCode, response.IsSuccessStatusCode ? "LangSmith connected" : "LangSmith unreachable", TimeSpan.Zero, DateTimeOffset.UtcNow);}catch (Exception ex){return new ConnectionHealth(false, $"LangSmith error: {ex.Message}", TimeSpan.Zero, DateTimeOffset.UtcNow);}}
    public override async Task<string> SendRequestAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var action = options?.GetValueOrDefault("action", "list_runs")?.ToString() ?? "list_runs";if (action == "create_run"){var name = options?.GetValueOrDefault("name", "run")?.ToString() ?? "run";var runType = options?.GetValueOrDefault("run_type", "chain")?.ToString() ?? "chain";var inputs = (options?.TryGetValue("inputs", out var inputsVal) == true ? inputsVal : null);var sessionName = options?.GetValueOrDefault("session_name", "default")?.ToString();var json = JsonSerializer.Serialize(new { name, run_type = runType, inputs, session_name = sessionName, start_time = DateTimeOffset.UtcNow });var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync("/api/v1/runs", content, ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}else if (action == "list_runs"){var sessionId = options?.GetValueOrDefault("session_id", "")?.ToString();var response = await httpClient.GetAsync($"/api/v1/runs?session_id={sessionId}&limit=100", ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}else if (action == "list_sessions"){var response = await httpClient.GetAsync("/api/v1/sessions?limit=100", ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}else if (action == "list_datasets"){var response = await httpClient.GetAsync("/api/v1/datasets?limit=100", ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}else if (action == "create_dataset"){var json = JsonSerializer.Serialize(new { name = prompt, description = options?.GetValueOrDefault("description", "") });var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync("/api/v1/datasets", content, ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}else{var response = await httpClient.GetAsync("/api/v1/sessions?limit=100", ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}}
    public override async IAsyncEnumerable<string> StreamResponseAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, [EnumeratorCancellation] CancellationToken ct = default){throw new NotSupportedException("LangSmith does not support streaming responses. Use SendRequestAsync for tracing and evaluation.");yield break;}
}
