using System;using System.Collections.Generic;using System.Net.Http;using System.Runtime.CompilerServices;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.AI;

/// <summary>llama.cpp server. REST API. Local GGUF model loading, completion, and chat with CPU/GPU inference.</summary>
public sealed class LlamaCppConnectionStrategy : AiConnectionStrategyBase
{
    public override string StrategyId => "ai-llamacpp";public override string DisplayName => "llama.cpp";public override ConnectionStrategyCapabilities Capabilities => new(SupportsPooling: false, SupportsStreaming: true, SupportsAuthentication: false);public override string SemanticDescription => "llama.cpp lightweight inference server. Local GGUF model loading with CPU and GPU support via REST API.";public override string[] Tags => ["llamacpp", "llm", "self-hosted", "local", "gguf", "cpu-inference"];
    public LlamaCppConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var baseUrl = config.ConnectionString ?? "http://localhost:8080";var httpClient = new HttpClient { BaseAddress = new Uri(baseUrl), Timeout = config.Timeout };return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "llama.cpp", ["BaseUrl"] = baseUrl });}
    protected override async Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct){var httpClient = handle.GetConnection<HttpClient>();var response = await httpClient.GetAsync("/health", ct);return response.IsSuccessStatusCode;}
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override async Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct){var httpClient = handle.GetConnection<HttpClient>();try{var response = await httpClient.GetAsync("/health", ct);if (response.IsSuccessStatusCode){var result = await response.Content.ReadAsStringAsync(ct);var doc = JsonDocument.Parse(result);var status = doc.RootElement.TryGetProperty("status", out var s) ? s.GetString() : "ok";return new ConnectionHealth(true, $"llama.cpp: {status}", TimeSpan.Zero, DateTimeOffset.UtcNow);}return new ConnectionHealth(false, "llama.cpp unreachable", TimeSpan.Zero, DateTimeOffset.UtcNow);}catch (Exception ex){return new ConnectionHealth(false, $"llama.cpp error: {ex.Message}", TimeSpan.Zero, DateTimeOffset.UtcNow);}}
    public override async Task<string> SendRequestAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var payload = new { prompt, n_predict = options?.GetValueOrDefault("max_tokens", 512) ?? 512, temperature = options?.GetValueOrDefault("temperature", 0.7), top_p = options?.GetValueOrDefault("top_p", 0.95), stop = options?.GetValueOrDefault("stop", new[] { "</s>" }), stream = false };var json = JsonSerializer.Serialize(payload);var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync("/completion", content, ct);response.EnsureSuccessStatusCode();var result = await response.Content.ReadAsStringAsync(ct);var doc = JsonDocument.Parse(result);return doc.RootElement.GetProperty("content").GetString() ?? "";}
    public override async IAsyncEnumerable<string> StreamResponseAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, [EnumeratorCancellation] CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var payload = new { prompt, n_predict = 512, temperature = 0.7, stream = true };var json = JsonSerializer.Serialize(payload);var content = new StringContent(json, Encoding.UTF8, "application/json");var request = new HttpRequestMessage(HttpMethod.Post, "/completion"){Content = content};var response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, ct);using var stream = await response.Content.ReadAsStreamAsync(ct);using var reader = new System.IO.StreamReader(stream);string? line;while (!ct.IsCancellationRequested && (line = await reader.ReadLineAsync(ct)) != null){if (string.IsNullOrEmpty(line) || !line.StartsWith("data: ")) continue;var data = line.Substring(6);string? chunk = null;bool shouldStop = false;try{var evt = JsonDocument.Parse(data);if (evt.RootElement.TryGetProperty("content", out var contentProp)){chunk = contentProp.GetString();}if (evt.RootElement.TryGetProperty("stop", out var stop) && stop.GetBoolean()) shouldStop = true;}catch{/* skip malformed */}if (chunk != null) yield return chunk;if (shouldStop) break;}}
}
