using System;using System.Collections.Generic;using System.Net.Http;using System.Net.Http.Headers;using System.Runtime.CompilerServices;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.AI;

/// <summary>LlamaIndex managed service (LlamaCloud). HTTPS to api.cloud.llamaindex.ai. Index management, document parsing, retrieval.</summary>
public sealed class LlamaIndexConnectionStrategy : AiConnectionStrategyBase
{
    public override string StrategyId => "ai-llamaindex";public override string DisplayName => "LlamaIndex Cloud";public override ConnectionStrategyCapabilities Capabilities => new() { SupportsPooling = false, SupportsStreaming = true, SupportsPooling = false, SupportsAuthentication = true };public override string SemanticDescription => "LlamaIndex Cloud managed RAG service. Document parsing, index management, retrieval-augmented generation pipelines.";public override string[] Tags => ["llamaindex", "llamacloud", "rag", "document-parsing", "retrieval", "indexing"];
    public LlamaIndexConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var baseUrl = config.ConnectionString ?? "https://api.cloud.llamaindex.ai";var httpClient = new HttpClient { BaseAddress = new Uri(baseUrl), Timeout = config.Timeout };if (config.Properties.TryGetValue("ApiKey", out var apiKey)){httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", apiKey.ToString()!);}return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "LlamaIndex", ["BaseUrl"] = baseUrl });}
    protected override async Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct){var httpClient = handle.GetConnection<HttpClient>();var response = await httpClient.GetAsync("/api/v1/pipelines", ct);return response.IsSuccessStatusCode;}
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override async Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct){var httpClient = handle.GetConnection<HttpClient>();try{var response = await httpClient.GetAsync("/api/v1/pipelines", ct);return new ConnectionHealth(response.IsSuccessStatusCode, response.IsSuccessStatusCode ? "LlamaIndex Cloud connected" : "LlamaIndex Cloud unreachable", TimeSpan.Zero, DateTimeOffset.UtcNow);}catch (Exception ex){return new ConnectionHealth(false, $"LlamaIndex error: {ex.Message}", TimeSpan.Zero, DateTimeOffset.UtcNow);}}
    public override async Task<string> SendRequestAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var action = options?.GetValueOrDefault("action", "query")?.ToString() ?? "query";var pipelineId = options?.GetValueOrDefault("pipeline_id", "")?.ToString() ?? "";if (action == "query"){var json = JsonSerializer.Serialize(new { query = prompt });var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync($"/api/v1/pipelines/{pipelineId}/retrieve", content, ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}else if (action == "list_pipelines"){var response = await httpClient.GetAsync("/api/v1/pipelines", ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}else if (action == "parse"){var json = JsonSerializer.Serialize(new { text = prompt });var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync("/api/v1/parsing/upload", content, ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}else{var response = await httpClient.GetAsync("/api/v1/pipelines", ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}}
    public override async IAsyncEnumerable<string> StreamResponseAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, [EnumeratorCancellation] CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var pipelineId = options?.GetValueOrDefault("pipeline_id", "")?.ToString() ?? "";var json = JsonSerializer.Serialize(new { query = prompt, stream = true });var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync($"/api/v1/pipelines/{pipelineId}/retrieve", content, HttpCompletionOption.ResponseHeadersRead, ct);using var stream = await response.Content.ReadAsStreamAsync(ct);using var reader = new System.IO.StreamReader(stream);while (!reader.EndOfStream && !ct.IsCancellationRequested){var line = await reader.ReadLineAsync(ct);if (string.IsNullOrEmpty(line) || !line.StartsWith("data: ")) continue;var data = line.Substring(6);if (data == "[DONE]") break;try{var evt = JsonDocument.Parse(data);if (evt.RootElement.TryGetProperty("response", out var text)){yield return text.GetString() ?? "";}}catch{continue;}}}
}
