using System;using System.Collections.Generic;using System.Net.Http;using System.Runtime.CompilerServices;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.AI;

/// <summary>Milvus vector database. REST/gRPC API. Collection management, partition support, similarity search.</summary>
public sealed class MilvusConnectionStrategy : AiConnectionStrategyBase
{
    public override string StrategyId => "ai-milvus";public override string DisplayName => "Milvus Vector DB";public override ConnectionStrategyCapabilities Capabilities => new(SupportsPooling: false, SupportsStreaming: false, SupportsAuthentication: true);public override string SemanticDescription => "Milvus open-source vector database. Scalable similarity search with partitions, indexes, and multi-vector support.";public override string[] Tags => ["milvus", "vector-db", "similarity-search", "partitions", "scalable"];
    public MilvusConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var baseUrl = config.ConnectionString ?? "http://localhost:19530";var httpClient = new HttpClient { BaseAddress = new Uri(baseUrl), Timeout = config.Timeout };if (config.Properties.TryGetValue("ApiKey", out var apiKey)){httpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {apiKey}");}return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "Milvus", ["BaseUrl"] = baseUrl });}
    protected override async Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct){var httpClient = handle.GetConnection<HttpClient>();using var response = await httpClient.GetAsync("/v2/vectordb/collections/list", ct);return response.IsSuccessStatusCode;}
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override async Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct){var httpClient = handle.GetConnection<HttpClient>();try{using var response = await httpClient.GetAsync("/v2/vectordb/collections/list", ct);return new ConnectionHealth(response.IsSuccessStatusCode, response.IsSuccessStatusCode ? "Milvus healthy" : "Milvus unreachable", TimeSpan.Zero, DateTimeOffset.UtcNow);}catch (Exception ex){return new ConnectionHealth(false, $"Milvus error: {ex.Message}", TimeSpan.Zero, DateTimeOffset.UtcNow);}}
    // Finding 1776: Validate expected vector dimension when provided in options.
    private static void ValidateVectorDimension(object? vector, Dictionary<string, object>? options)
    {
        if (vector == null) return;
        if (options?.TryGetValue("expected_dim", out var dimVal) == true && dimVal != null
            && int.TryParse(dimVal.ToString(), out var expectedDim) && expectedDim > 0)
        {
            if (vector is System.Collections.IList list && list.Count != expectedDim)
                throw new ArgumentException($"Vector dimension mismatch: expected {expectedDim}, got {list.Count}.");
        }
    }
    public override async Task<string> SendRequestAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var action = options?.GetValueOrDefault("action", "search")?.ToString() ?? "search";var collection = options?.GetValueOrDefault("collection", "default")?.ToString() ?? "default";if (action == "insert"){var data = (options?.TryGetValue("data", out var dataVal) == true ? dataVal : null);var json = JsonSerializer.Serialize(new { collectionName = collection, data });using var content = new StringContent(json, Encoding.UTF8, "application/json");using var response = await httpClient.PostAsync("/v2/vectordb/entities/insert", content, ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}else if (action == "search"){var vector = (options?.TryGetValue("vector", out var vectorVal) == true ? vectorVal : null);ValidateVectorDimension(vector, options);var limit = options?.GetValueOrDefault("limit", 10) ?? 10;var json = JsonSerializer.Serialize(new { collectionName = collection, vector, limit });using var content = new StringContent(json, Encoding.UTF8, "application/json");using var response = await httpClient.PostAsync("/v2/vectordb/entities/search", content, ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}else{var json = JsonSerializer.Serialize(new { collectionName = collection });using var content = new StringContent(json, Encoding.UTF8, "application/json");using var response = await httpClient.PostAsync("/v2/vectordb/collections/describe", content, ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}}
    public override async IAsyncEnumerable<string> StreamResponseAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, [EnumeratorCancellation] CancellationToken ct = default){ThrowStreamingNotSupported("Milvus does not support streaming responses. Use SendRequestAsync for vector operations.");yield break;}
}
