using System;using System.Collections.Generic;using System.Net.Http;using System.Runtime.CompilerServices;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.AI;

/// <summary>MLflow Tracking Server. REST API for experiment/run management, model registry, artifact logging.</summary>
public sealed class MlFlowConnectionStrategy : AiConnectionStrategyBase
{
    public override string StrategyId => "ai-mlflow";public override string DisplayName => "MLflow";public override ConnectionStrategyCapabilities Capabilities => new(SupportsPooling: false, SupportsStreaming: false, SupportsAuthentication: true);public override string SemanticDescription => "MLflow open-source ML lifecycle platform. Experiment tracking, model registry, and artifact management via REST API.";public override string[] Tags => ["mlflow", "ml-platform", "experiment-tracking", "model-registry", "artifacts"];
    public MlFlowConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var baseUrl = config.ConnectionString ?? "http://localhost:5000";var httpClient = new HttpClient { BaseAddress = new Uri(baseUrl), Timeout = config.Timeout };if (config.Properties.TryGetValue("ApiKey", out var apiKey)){httpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {apiKey}");}return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "MLflow", ["BaseUrl"] = baseUrl });}
    protected override async Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct){var httpClient = handle.GetConnection<HttpClient>();var response = await httpClient.GetAsync("/api/2.0/mlflow/experiments/search?max_results=1", ct);return response.IsSuccessStatusCode;}
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override async Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct){var httpClient = handle.GetConnection<HttpClient>();try{var response = await httpClient.GetAsync("/api/2.0/mlflow/experiments/search?max_results=1", ct);return new ConnectionHealth(response.IsSuccessStatusCode, response.IsSuccessStatusCode ? "MLflow server available" : "MLflow unreachable", TimeSpan.Zero, DateTimeOffset.UtcNow);}catch (Exception ex){return new ConnectionHealth(false, $"MLflow error: {ex.Message}", TimeSpan.Zero, DateTimeOffset.UtcNow);}}
    public override async Task<string> SendRequestAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var action = options?.GetValueOrDefault("action", "search_experiments")?.ToString() ?? "search_experiments";if (action == "create_experiment"){var name = options?.GetValueOrDefault("name", prompt)?.ToString() ?? prompt;var json = JsonSerializer.Serialize(new { name });var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync("/api/2.0/mlflow/experiments/create", content, ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}else if (action == "create_run"){var experimentId = options?.GetValueOrDefault("experiment_id", "0")?.ToString() ?? "0";var json = JsonSerializer.Serialize(new { experiment_id = experimentId, start_time = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds() });var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync("/api/2.0/mlflow/runs/create", content, ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}else if (action == "log_metric"){var runId = options?.GetValueOrDefault("run_id", "")?.ToString();var key = options?.GetValueOrDefault("key", "metric")?.ToString();var value = options?.GetValueOrDefault("value", 0.0);var json = JsonSerializer.Serialize(new { run_id = runId, key, value, timestamp = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds() });var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync("/api/2.0/mlflow/runs/log-metric", content, ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}else{var response = await httpClient.GetAsync("/api/2.0/mlflow/experiments/search?max_results=100", ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}}
    public override async IAsyncEnumerable<string> StreamResponseAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, [EnumeratorCancellation] CancellationToken ct = default){throw new NotSupportedException("MLflow does not support streaming responses. Use SendRequestAsync for experiment management.");yield break;}
}
