using System;using System.Collections.Generic;using System.Net.Http;using System.Net.Http.Headers;using System.Runtime.CompilerServices;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.AI;

/// <summary>OpenAI connection strategy. HTTPS to api.openai.com/v1, Bearer token auth. GPT-4o, o1, o3 models.</summary>
public sealed class OpenAiConnectionStrategy : AiConnectionStrategyBase
{
    public override string StrategyId => "openai";public override string DisplayName => "OpenAI";public override ConnectionStrategyCapabilities Capabilities => new();public override string SemanticDescription => "OpenAI GPT models. ChatGPT, GPT-4o, o1, o3. Leading LLM provider with embeddings and vision.";public override string[] Tags => ["openai", "llm", "gpt", "chatgpt", "embeddings", "vision"];
    public OpenAiConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var httpClient = new HttpClient { BaseAddress = new Uri("https://api.openai.com/v1"), Timeout = config.Timeout };if (config.Properties.TryGetValue("ApiKey", out var apiKey)){httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", apiKey.ToString()!);}return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "OpenAI" });}
    protected override Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct) => Task.FromResult(true);
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct) => Task.FromResult(new ConnectionHealth(true, "OpenAI configured", TimeSpan.Zero, DateTimeOffset.UtcNow));
    public override async Task<string> SendRequestAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var payload = new { model = options?.GetValueOrDefault("model", "gpt-4o") ?? "gpt-4o", messages = new[] { new { role = "user", content = prompt } }, temperature = options?.GetValueOrDefault("temperature", 0.7) };var json = JsonSerializer.Serialize(payload);var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync("/chat/completions", content, ct);response.EnsureSuccessStatusCode();var result = await response.Content.ReadAsStringAsync(ct);var doc = JsonDocument.Parse(result);return doc.RootElement.GetProperty("choices")[0].GetProperty("message").GetProperty("content").GetString() ?? "";}
    public override async IAsyncEnumerable<string> StreamResponseAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, [EnumeratorCancellation] CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var payload = new { model = options?.GetValueOrDefault("model", "gpt-4o") ?? "gpt-4o", messages = new[] { new { role = "user", content = prompt } }, stream = true };var json = JsonSerializer.Serialize(payload);var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync("/chat/completions", content, HttpCompletionOption.ResponseHeadersRead, ct);using var stream = await response.Content.ReadAsStreamAsync(ct);using var reader = new System.IO.StreamReader(stream);while (!reader.EndOfStream && !ct.IsCancellationRequested){var line = await reader.ReadLineAsync(ct);if (string.IsNullOrEmpty(line) || !line.StartsWith("data: ")) continue;var data = line.Substring(6);if (data == "[DONE]") break;try{var evt = JsonDocument.Parse(data);var delta = evt.RootElement.GetProperty("choices")[0].GetProperty("delta");if (delta.TryGetProperty("content", out var contentProp)){yield return contentProp.GetString() ?? "";}}catch{continue;}}}
}
