using System;using System.Collections.Generic;using System.Net.Http;using System.Runtime.CompilerServices;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;using Npgsql;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.AI;

/// <summary>PostgreSQL pgvector extension. Npgsql connection for vector operations. Embedding storage and cosine/L2 similarity search.</summary>
public sealed class PgVectorConnectionStrategy : AiConnectionStrategyBase
{
    public override string StrategyId => "ai-pgvector";public override string DisplayName => "PostgreSQL pgvector";public override ConnectionStrategyCapabilities Capabilities => new(SupportsPooling: true, SupportsStreaming: false, SupportsAuthentication: true);public override string SemanticDescription => "PostgreSQL pgvector extension for vector similarity search. Cosine, L2, inner product distance with HNSW and IVFFlat indexes.";public override string[] Tags => ["pgvector", "postgresql", "vector-db", "sql", "embeddings", "hnsw"];
    public PgVectorConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var connectionString = config.ConnectionString ?? throw new ArgumentException("PostgreSQL connection string required");var conn = new NpgsqlConnection(connectionString);await conn.OpenAsync(ct);using var cmd = conn.CreateCommand();cmd.CommandText = "CREATE EXTENSION IF NOT EXISTS vector";await cmd.ExecuteNonQueryAsync(ct);return new DefaultConnectionHandle(conn, new Dictionary<string, object> { ["Provider"] = "PgVector", ["Database"] = conn.Database ?? "" });}
    protected override async Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct){var conn = handle.GetConnection<NpgsqlConnection>();using var cmd = conn.CreateCommand();cmd.CommandText = "SELECT 1";var result = await cmd.ExecuteScalarAsync(ct);return result != null;}
    protected override async Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){var conn = handle.GetConnection<NpgsqlConnection>();await conn.CloseAsync();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();}
    protected override async Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct){try{var conn = handle.GetConnection<NpgsqlConnection>();using var cmd = conn.CreateCommand();cmd.CommandText = "SELECT extversion FROM pg_extension WHERE extname = 'vector'";var version = await cmd.ExecuteScalarAsync(ct);return new ConnectionHealth(version != null, version != null ? $"pgvector v{version} active" : "pgvector extension not found", TimeSpan.Zero, DateTimeOffset.UtcNow);}catch (Exception ex){return new ConnectionHealth(false, $"PgVector error: {ex.Message}", TimeSpan.Zero, DateTimeOffset.UtcNow);}}
    public override async Task<string> SendRequestAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, CancellationToken ct = default){var conn = handle.GetConnection<NpgsqlConnection>();var action = options?.GetValueOrDefault("action", "query")?.ToString() ?? "query";if (action == "query"){using var cmd = conn.CreateCommand();cmd.CommandText = prompt;using var reader = await cmd.ExecuteReaderAsync(ct);var results = new List<Dictionary<string, object?>>();while (await reader.ReadAsync(ct)){var row = new Dictionary<string, object?>();for (int i = 0; i < reader.FieldCount; i++){row[reader.GetName(i)] = reader.IsDBNull(i) ? null : reader.GetValue(i);}results.Add(row);}return JsonSerializer.Serialize(results);}else{using var cmd = conn.CreateCommand();cmd.CommandText = prompt;var affected = await cmd.ExecuteNonQueryAsync(ct);return JsonSerializer.Serialize(new { affected });}}
    public override async IAsyncEnumerable<string> StreamResponseAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, [EnumeratorCancellation] CancellationToken ct = default){ThrowStreamingNotSupported("PgVector does not support streaming responses. Use SendRequestAsync for SQL vector operations.");yield break;}
}
