using System;using System.Collections.Generic;using System.Net.Http;using System.Net.Http.Headers;using System.Runtime.CompilerServices;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.AI;

/// <summary>Qdrant vector database. REST/gRPC API. Collection management, similarity search with filtering.</summary>
public sealed class QdrantConnectionStrategy : AiConnectionStrategyBase
{
    public override string StrategyId => "ai-qdrant";public override string DisplayName => "Qdrant Vector DB";public override ConnectionStrategyCapabilities Capabilities => new(SupportsPooling: false, SupportsStreaming: false, SupportsAuthentication: true);public override string SemanticDescription => "Qdrant high-performance vector database. Similarity search with advanced filtering, payload indexing and quantization.";public override string[] Tags => ["qdrant", "vector-db", "similarity-search", "filtering", "grpc"];
    public QdrantConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var baseUrl = config.ConnectionString ?? "http://localhost:6333";var httpClient = new HttpClient { BaseAddress = new Uri(baseUrl), Timeout = config.Timeout };if (config.Properties.TryGetValue("ApiKey", out var apiKey)){httpClient.DefaultRequestHeaders.Add("api-key", apiKey.ToString()!);}return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "Qdrant", ["BaseUrl"] = baseUrl });}
    protected override async Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct){var httpClient = handle.GetConnection<HttpClient>();var response = await httpClient.GetAsync("/healthz", ct);return response.IsSuccessStatusCode;}
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override async Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct){var httpClient = handle.GetConnection<HttpClient>();try{var response = await httpClient.GetAsync("/healthz", ct);return new ConnectionHealth(response.IsSuccessStatusCode, response.IsSuccessStatusCode ? "Qdrant healthy" : "Qdrant unreachable", TimeSpan.Zero, DateTimeOffset.UtcNow);}catch (Exception ex){return new ConnectionHealth(false, $"Qdrant error: {ex.Message}", TimeSpan.Zero, DateTimeOffset.UtcNow);}}
    public override async Task<string> SendRequestAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var action = options?.GetValueOrDefault("action", "search")?.ToString() ?? "search";var collection = options?.GetValueOrDefault("collection", "default")?.ToString() ?? "default";if (action == "upsert"){var points = (options?.TryGetValue("points", out var pointsVal) == true ? pointsVal : null);var json = JsonSerializer.Serialize(new { points });var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PutAsync($"/collections/{collection}/points", content, ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}else if (action == "search"){var vector = (options?.TryGetValue("vector", out var vectorVal) == true ? vectorVal : null);var limit = options?.GetValueOrDefault("limit", 10) ?? 10;var filter = (options?.TryGetValue("filter", out var filterVal) == true ? filterVal : null);var json = JsonSerializer.Serialize(new { vector, limit, filter, with_payload = true });var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync($"/collections/{collection}/points/search", content, ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}else{var response = await httpClient.GetAsync($"/collections/{collection}", ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}}
    public override async IAsyncEnumerable<string> StreamResponseAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, [EnumeratorCancellation] CancellationToken ct = default){throw new NotSupportedException("Qdrant does not support streaming responses. Use SendRequestAsync for vector operations.");yield break;}
}
