using System;using System.Collections.Generic;using System.Net.Http;using System.Net.Http.Headers;using System.Runtime.CompilerServices;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.AI;

/// <summary>Stability AI. HTTPS to api.stability.ai/v1. Stable Diffusion image generation, upscaling, inpainting.</summary>
public sealed class StabilityAiConnectionStrategy : AiConnectionStrategyBase
{
    public override string StrategyId => "ai-stability";public override string DisplayName => "Stability AI";public override ConnectionStrategyCapabilities Capabilities => new(SupportsPooling: false, SupportsStreaming: false, SupportsAuthentication: true);public override string SemanticDescription => "Stability AI image generation platform. Stable Diffusion models for text-to-image, image-to-image, upscaling, and inpainting.";public override string[] Tags => ["stability", "stable-diffusion", "image-generation", "text-to-image", "diffusion"];
    public StabilityAiConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var httpClient = new HttpClient { BaseAddress = new Uri("https://api.stability.ai"), Timeout = config.Timeout };if (config.Properties.TryGetValue("ApiKey", out var apiKey)){httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", apiKey.ToString()!);}return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "StabilityAI" });}
    protected override async Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct){var httpClient = handle.GetConnection<HttpClient>();using var response = await httpClient.GetAsync("/v1/engines/list", ct);return response.IsSuccessStatusCode;}
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override async Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct){var httpClient = handle.GetConnection<HttpClient>();try{using var response = await httpClient.GetAsync("/v1/user/account", ct);return new ConnectionHealth(response.IsSuccessStatusCode, response.IsSuccessStatusCode ? "Stability AI connected" : "Stability AI unreachable", TimeSpan.Zero, DateTimeOffset.UtcNow);}catch (Exception ex){return new ConnectionHealth(false, $"Stability AI error: {ex.Message}", TimeSpan.Zero, DateTimeOffset.UtcNow);}}
    public override async Task<string> SendRequestAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var action = options?.GetValueOrDefault("action", "text-to-image")?.ToString() ?? "text-to-image";var engine = options?.GetValueOrDefault("engine", "stable-diffusion-xl-1024-v1-0")?.ToString() ?? "stable-diffusion-xl-1024-v1-0";if (action == "text-to-image"){var payload = new { text_prompts = new[] { new { text = prompt, weight = 1.0 } }, cfg_scale = options?.GetValueOrDefault("cfg_scale", 7) ?? 7, height = options?.GetValueOrDefault("height", 1024) ?? 1024, width = options?.GetValueOrDefault("width", 1024) ?? 1024, steps = options?.GetValueOrDefault("steps", 30) ?? 30, samples = 1 };var json = JsonSerializer.Serialize(payload);using var content = new StringContent(json, Encoding.UTF8, "application/json");content.Headers.Add("Accept", "application/json");using var response = await httpClient.PostAsync($"/v1/generation/{engine}/text-to-image", content, ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}else if (action == "engines"){using var response = await httpClient.GetAsync("/v1/engines/list", ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}else{using var response = await httpClient.GetAsync("/v1/user/balance", ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}}
    public override async IAsyncEnumerable<string> StreamResponseAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, [EnumeratorCancellation] CancellationToken ct = default){ThrowStreamingNotSupported("Stability AI does not support streaming responses. Use SendRequestAsync for image generation.");yield break;}
}
