using System;using System.Collections.Generic;using System.Net.Http;using System.Net.Http.Headers;using System.Runtime.CompilerServices;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.AI;

/// <summary>HuggingFace Text Generation Inference (TGI). REST API. Optimized transformer inference with continuous batching.</summary>
public sealed class TgiConnectionStrategy : AiConnectionStrategyBase
{
    public override string StrategyId => "ai-tgi";public override string DisplayName => "HuggingFace TGI";public override ConnectionStrategyCapabilities Capabilities => new(SupportsPooling: false, SupportsStreaming: true, SupportsAuthentication: false);public override string SemanticDescription => "HuggingFace Text Generation Inference server. Optimized transformer serving with continuous batching, quantization, and tensor parallelism.";public override string[] Tags => ["tgi", "huggingface", "self-hosted", "inference", "transformers", "text-generation"];
    public TgiConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var baseUrl = config.ConnectionString ?? "http://localhost:8080";var httpClient = new HttpClient { BaseAddress = new Uri(baseUrl), Timeout = config.Timeout };if (config.Properties.TryGetValue("ApiKey", out var apiKey)){httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", apiKey.ToString()!);}return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "TGI", ["BaseUrl"] = baseUrl });}
    protected override async Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct){var httpClient = handle.GetConnection<HttpClient>();var response = await httpClient.GetAsync("/health", ct);return response.IsSuccessStatusCode;}
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override async Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct){var httpClient = handle.GetConnection<HttpClient>();try{var response = await httpClient.GetAsync("/health", ct);return new ConnectionHealth(response.IsSuccessStatusCode, response.IsSuccessStatusCode ? "TGI healthy" : "TGI unreachable", TimeSpan.Zero, DateTimeOffset.UtcNow);}catch (Exception ex){return new ConnectionHealth(false, $"TGI error: {ex.Message}", TimeSpan.Zero, DateTimeOffset.UtcNow);}}
    public override async Task<string> SendRequestAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var payload = new { inputs = prompt, parameters = new { max_new_tokens = options?.GetValueOrDefault("max_tokens", 512) ?? 512, temperature = options?.GetValueOrDefault("temperature", 0.7), top_p = options?.GetValueOrDefault("top_p", 0.95), repetition_penalty = options?.GetValueOrDefault("repetition_penalty", 1.1) } };var json = JsonSerializer.Serialize(payload);var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync("/generate", content, ct);response.EnsureSuccessStatusCode();var result = await response.Content.ReadAsStringAsync(ct);var doc = JsonDocument.Parse(result);return doc.RootElement.GetProperty("generated_text").GetString() ?? "";}
    public override async IAsyncEnumerable<string> StreamResponseAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, [EnumeratorCancellation] CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var payload = new { inputs = prompt, parameters = new { max_new_tokens = 512, temperature = 0.7 } };var json = JsonSerializer.Serialize(payload);var content = new StringContent(json, Encoding.UTF8, "application/json");var request = new HttpRequestMessage(HttpMethod.Post, "/generate_stream"){Content = content};var response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, ct);using var stream = await response.Content.ReadAsStreamAsync(ct);using var reader = new System.IO.StreamReader(stream);string? line;while (!ct.IsCancellationRequested && (line = await reader.ReadLineAsync(ct)) != null){if (string.IsNullOrEmpty(line) || !line.StartsWith("data:")) continue;var data = line.StartsWith("data: ") ? line.Substring(6) : line.Substring(5);string? chunk = null;try{var evt = JsonDocument.Parse(data);if (evt.RootElement.TryGetProperty("token", out var token) && token.TryGetProperty("text", out var text)){var special = token.TryGetProperty("special", out var sp) && sp.GetBoolean();if (!special) chunk = text.GetString();}}catch{/* skip malformed */}if (chunk != null) yield return chunk;}}
}
