using System;using System.Collections.Generic;using System.Net.Http;using System.Runtime.CompilerServices;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.AI;

/// <summary>NVIDIA Triton Inference Server. REST/gRPC API. Multi-framework model repository, dynamic batching, ensemble pipelines.</summary>
public sealed class TritonConnectionStrategy : AiConnectionStrategyBase
{
    public override string StrategyId => "ai-triton";public override string DisplayName => "NVIDIA Triton";public override ConnectionStrategyCapabilities Capabilities => new(SupportsPooling: false, SupportsStreaming: true, SupportsAuthentication: false);public override string SemanticDescription => "NVIDIA Triton Inference Server. Multi-framework model serving with dynamic batching, model ensembles, and GPU/CPU optimization.";public override string[] Tags => ["triton", "nvidia", "self-hosted", "inference", "multi-framework", "gpu"];
    public TritonConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var baseUrl = config.ConnectionString ?? "http://localhost:8000";var httpClient = new HttpClient { BaseAddress = new Uri(baseUrl), Timeout = config.Timeout };return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "Triton", ["BaseUrl"] = baseUrl });}
    protected override async Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct){var httpClient = handle.GetConnection<HttpClient>();var response = await httpClient.GetAsync("/v2/health/ready", ct);return response.IsSuccessStatusCode;}
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override async Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct){var httpClient = handle.GetConnection<HttpClient>();try{var live = await httpClient.GetAsync("/v2/health/live", ct);var ready = await httpClient.GetAsync("/v2/health/ready", ct);var isHealthy = live.IsSuccessStatusCode && ready.IsSuccessStatusCode;return new ConnectionHealth(isHealthy, isHealthy ? "Triton live and ready" : "Triton not ready", TimeSpan.Zero, DateTimeOffset.UtcNow);}catch (Exception ex){return new ConnectionHealth(false, $"Triton error: {ex.Message}", TimeSpan.Zero, DateTimeOffset.UtcNow);}}
    public override async Task<string> SendRequestAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var action = options?.GetValueOrDefault("action", "infer")?.ToString() ?? "infer";var model = options?.GetValueOrDefault("model", "")?.ToString() ?? "";if (action == "infer"){var inputs = (options?.TryGetValue("inputs", out var inputsVal) == true ? inputsVal : null);var json = inputs != null ? JsonSerializer.Serialize(new { inputs }) : JsonSerializer.Serialize(new { inputs = new[] { new { name = "text_input", shape = new[] { 1 }, datatype = "BYTES", data = new[] { prompt } } } });var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync($"/v2/models/{model}/infer", content, ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}else if (action == "model_config"){var response = await httpClient.GetAsync($"/v2/models/{model}/config", ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}else{var response = await httpClient.GetAsync("/v2/models", ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}}
    public override async IAsyncEnumerable<string> StreamResponseAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, [EnumeratorCancellation] CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var model = options?.GetValueOrDefault("model", "")?.ToString() ?? "";var json = JsonSerializer.Serialize(new { inputs = new[] { new { name = "text_input", shape = new[] { 1 }, datatype = "BYTES", data = new[] { prompt } } }, parameters = new { stream = true } });var content = new StringContent(json, Encoding.UTF8, "application/json");var request = new HttpRequestMessage(HttpMethod.Post, $"/v2/models/{model}/generate_stream"){Content = content};var response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, ct);using var stream = await response.Content.ReadAsStreamAsync(ct);using var reader = new System.IO.StreamReader(stream);while (!reader.EndOfStream && !ct.IsCancellationRequested){var line = await reader.ReadLineAsync(ct);if (string.IsNullOrEmpty(line) || !line.StartsWith("data:")) continue;var data = line.StartsWith("data: ") ? line.Substring(6) : line.Substring(5);string? chunk = null;try{var evt = JsonDocument.Parse(data);if (evt.RootElement.TryGetProperty("outputs", out var outputs) && outputs.GetArrayLength() > 0){var outputData = outputs[0].GetProperty("data");if (outputData.GetArrayLength() > 0) chunk = outputData[0].GetString();}}catch{/* skip malformed */}if (chunk != null) yield return chunk;}}
}
