using System;using System.Collections.Generic;using System.Net.Http;using System.Net.Http.Headers;using System.Runtime.CompilerServices;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.AI;

/// <summary>Google Vertex AI. HTTPS to *-aiplatform.googleapis.com. Model deployment, predictions, managed endpoints.</summary>
public sealed class VertexAiConnectionStrategy : AiConnectionStrategyBase
{
    public override string StrategyId => "ai-vertex";public override string DisplayName => "Google Vertex AI";public override ConnectionStrategyCapabilities Capabilities => new(SupportsPooling: false, SupportsStreaming: true, SupportsAuthentication: true);public override string SemanticDescription => "Google Vertex AI managed ML platform. Model deployment, online predictions, AutoML, and Gemini integration.";public override string[] Tags => ["google", "vertex-ai", "ml-platform", "predictions", "automl", "gemini"];
    public VertexAiConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var project = config.Properties.GetValueOrDefault("ProjectId", "")?.ToString() ?? "";var region = config.Properties.GetValueOrDefault("Region", "us-central1")?.ToString() ?? "us-central1";var baseUrl = $"https://{Uri.EscapeDataString(region ?? "")}-aiplatform.googleapis.com";var httpClient = new HttpClient { BaseAddress = new Uri(baseUrl), Timeout = config.Timeout };if (config.Properties.TryGetValue("AccessToken", out var token)){httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token.ToString()!);}return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "VertexAI", ["ProjectId"] = project!, ["Region"] = region! });}
    protected override async Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct){try{var httpClient = handle.GetConnection<HttpClient>();using var response = await httpClient.GetAsync("/", ct);return response.IsSuccessStatusCode;}catch{return false;}}
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override async Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct){var sw = System.Diagnostics.Stopwatch.StartNew();try{var httpClient = handle.GetConnection<HttpClient>();using var response = await httpClient.GetAsync("/", ct);sw.Stop();return new ConnectionHealth(response.IsSuccessStatusCode, response.IsSuccessStatusCode ? "VertexAi connected" : "VertexAi error: HTTP " + (int)response.StatusCode, sw.Elapsed, DateTimeOffset.UtcNow);}catch(Exception ex){sw.Stop();return new ConnectionHealth(false, $"VertexAi error: {ex.Message}", sw.Elapsed, DateTimeOffset.UtcNow);}}
    public override async Task<string> SendRequestAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var project = handle.ConnectionInfo["ProjectId"]?.ToString();var region = handle.ConnectionInfo["Region"]?.ToString();var model = options?.GetValueOrDefault("model", "gemini-pro")?.ToString() ?? "gemini-pro";var payload = new { contents = new[] { new { parts = new[] { new { text = prompt } } } } };var json = JsonSerializer.Serialize(payload);using var content = new StringContent(json, Encoding.UTF8, "application/json");using var response = await httpClient.PostAsync($"/v1/projects/{Uri.EscapeDataString(project ?? "")}/locations/{Uri.EscapeDataString(region ?? "")}/publishers/google/models/{Uri.EscapeDataString(model)}:generateContent", content, ct);response.EnsureSuccessStatusCode();var result = await response.Content.ReadAsStringAsync(ct);using var doc = JsonDocument.Parse(result);if (doc.RootElement.TryGetProperty("candidates", out var candidates) && candidates.GetArrayLength() > 0){return candidates[0].GetProperty("content").GetProperty("parts")[0].GetProperty("text").GetString() ?? candidates[0].ToString();}return result;}
    public override async IAsyncEnumerable<string> StreamResponseAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, [EnumeratorCancellation] CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var project = handle.ConnectionInfo["ProjectId"]?.ToString();var region = handle.ConnectionInfo["Region"]?.ToString();var model = options?.GetValueOrDefault("model", "gemini-pro")?.ToString() ?? "gemini-pro";var payload = new { contents = new[] { new { parts = new[] { new { text = prompt } } } } };var json = JsonSerializer.Serialize(payload);using var content = new StringContent(json, Encoding.UTF8, "application/json");var request = new HttpRequestMessage(HttpMethod.Post, $"/v1/projects/{Uri.EscapeDataString(project ?? "")}/locations/{Uri.EscapeDataString(region ?? "")}/publishers/google/models/{Uri.EscapeDataString(model)}:streamGenerateContent"){Content = content};using var response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, ct);using var stream = await response.Content.ReadAsStreamAsync(ct);using var reader = new System.IO.StreamReader(stream);string? line;while (!ct.IsCancellationRequested && (line = await reader.ReadLineAsync(ct)) != null){if (string.IsNullOrEmpty(line)) continue;string? chunk = null;try{using var evt = JsonDocument.Parse(line);if (evt.RootElement.TryGetProperty("candidates", out var candidates) && candidates.GetArrayLength() > 0){chunk = candidates[0].GetProperty("content").GetProperty("parts")[0].GetProperty("text").GetString();}}catch{/* skip malformed */}if (chunk != null) yield return chunk;}}
}
