using System;using System.Collections.Generic;using System.Net.Http;using System.Net.Http.Headers;using System.Runtime.CompilerServices;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.AI;

/// <summary>Google Vertex AI. HTTPS to *-aiplatform.googleapis.com. Model deployment, predictions, managed endpoints.</summary>
public sealed class VertexAiConnectionStrategy : AiConnectionStrategyBase
{
    public override string StrategyId => "ai-vertex";public override string DisplayName => "Google Vertex AI";public override ConnectionStrategyCapabilities Capabilities => new(SupportsPooling: false, SupportsStreaming: true, SupportsAuthentication: true);public override string SemanticDescription => "Google Vertex AI managed ML platform. Model deployment, online predictions, AutoML, and Gemini integration.";public override string[] Tags => ["google", "vertex-ai", "ml-platform", "predictions", "automl", "gemini"];
    public VertexAiConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var project = config.Properties.GetValueOrDefault("ProjectId", "")?.ToString() ?? "";var region = config.Properties.GetValueOrDefault("Region", "us-central1")?.ToString() ?? "us-central1";var baseUrl = $"https://{region}-aiplatform.googleapis.com";var httpClient = new HttpClient { BaseAddress = new Uri(baseUrl), Timeout = config.Timeout };if (config.Properties.TryGetValue("AccessToken", out var token)){httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token.ToString()!);}return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "VertexAI", ["ProjectId"] = project, ["Region"] = region });}
    protected override Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct) => Task.FromResult(true);
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct) => Task.FromResult(new ConnectionHealth(true, "Vertex AI configured", TimeSpan.Zero, DateTimeOffset.UtcNow));
    public override async Task<string> SendRequestAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var project = handle.ConnectionInfo["ProjectId"]?.ToString();var region = handle.ConnectionInfo["Region"]?.ToString();var model = options?.GetValueOrDefault("model", "gemini-pro")?.ToString() ?? "gemini-pro";var payload = new { instances = new[] { new { content = prompt } } };var json = JsonSerializer.Serialize(payload);var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync($"/v1/projects/{project}/locations/{region}/publishers/google/models/{model}:predict", content, ct);response.EnsureSuccessStatusCode();var result = await response.Content.ReadAsStringAsync(ct);var doc = JsonDocument.Parse(result);if (doc.RootElement.TryGetProperty("predictions", out var predictions) && predictions.GetArrayLength() > 0){return predictions[0].GetProperty("content").GetString() ?? predictions[0].ToString();}return result;}
    public override async IAsyncEnumerable<string> StreamResponseAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, [EnumeratorCancellation] CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var project = handle.ConnectionInfo["ProjectId"]?.ToString();var region = handle.ConnectionInfo["Region"]?.ToString();var model = options?.GetValueOrDefault("model", "gemini-pro")?.ToString() ?? "gemini-pro";var payload = new { contents = new[] { new { parts = new[] { new { text = prompt } } } } };var json = JsonSerializer.Serialize(payload);var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync($"/v1/projects/{project}/locations/{region}/publishers/google/models/{model}:streamGenerateContent", content, HttpCompletionOption.ResponseHeadersRead, ct);using var stream = await response.Content.ReadAsStreamAsync(ct);using var reader = new System.IO.StreamReader(stream);while (!reader.EndOfStream && !ct.IsCancellationRequested){var line = await reader.ReadLineAsync(ct);if (string.IsNullOrEmpty(line)) continue;try{var evt = JsonDocument.Parse(line);if (evt.RootElement.TryGetProperty("candidates", out var candidates) && candidates.GetArrayLength() > 0){var text = candidates[0].GetProperty("content").GetProperty("parts")[0].GetProperty("text").GetString();if (text != null) yield return text;}}catch{continue;}}}
}
