using System;using System.Collections.Generic;using System.Net.Http;using System.Net.Http.Headers;using System.Runtime.CompilerServices;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.AI;

/// <summary>Weaviate vector database. REST/GraphQL API. Schema management, vector+keyword hybrid search.</summary>
public sealed class WeaviateConnectionStrategy : AiConnectionStrategyBase
{
    public override string StrategyId => "ai-weaviate";public override string DisplayName => "Weaviate Vector DB";public override ConnectionStrategyCapabilities Capabilities => new(SupportsPooling: false, SupportsStreaming: false, SupportsAuthentication: true);public override string SemanticDescription => "Weaviate open-source vector database. Hybrid vector+keyword search with GraphQL API and multi-tenancy.";public override string[] Tags => ["weaviate", "vector-db", "graphql", "hybrid-search", "multi-tenancy"];
    public WeaviateConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var baseUrl = config.ConnectionString ?? "http://localhost:8080";var httpClient = new HttpClient { BaseAddress = new Uri(baseUrl), Timeout = config.Timeout };if (config.Properties.TryGetValue("ApiKey", out var apiKey)){httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", apiKey.ToString()!);}return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "Weaviate", ["BaseUrl"] = baseUrl });}
    protected override async Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct){var httpClient = handle.GetConnection<HttpClient>();var response = await httpClient.GetAsync("/v1/.well-known/ready", ct);return response.IsSuccessStatusCode;}
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override async Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct){var httpClient = handle.GetConnection<HttpClient>();try{var response = await httpClient.GetAsync("/v1/.well-known/ready", ct);return new ConnectionHealth(response.IsSuccessStatusCode, response.IsSuccessStatusCode ? "Weaviate ready" : "Weaviate not ready", TimeSpan.Zero, DateTimeOffset.UtcNow);}catch (Exception ex){return new ConnectionHealth(false, $"Weaviate error: {ex.Message}", TimeSpan.Zero, DateTimeOffset.UtcNow);}}
    public override async Task<string> SendRequestAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var action = options?.GetValueOrDefault("action", "graphql")?.ToString() ?? "graphql";if (action == "graphql"){var json = JsonSerializer.Serialize(new { query = prompt });var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync("/v1/graphql", content, ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}else if (action == "objects"){var className = options?.GetValueOrDefault("class", "")?.ToString();var properties = (options?.TryGetValue("properties", out var propsVal) == true ? propsVal : null);var json = JsonSerializer.Serialize(new { @class = className, properties });var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync("/v1/objects", content, ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}else{var response = await httpClient.GetAsync($"/v1/schema", ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}}
    public override async IAsyncEnumerable<string> StreamResponseAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, [EnumeratorCancellation] CancellationToken ct = default){throw new NotSupportedException("Weaviate does not support streaming responses. Use SendRequestAsync for vector operations.");yield break;}
}
