using System;using System.Collections.Generic;using System.Net.Http;using System.Net.Http.Headers;using System.Runtime.CompilerServices;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.AI;

/// <summary>Weights & Biases. HTTPS to api.wandb.ai. Run logging, artifact management, experiment tracking.</summary>
public sealed class WeightsAndBiasesConnectionStrategy : AiConnectionStrategyBase
{
    public override string StrategyId => "ai-wandb";public override string DisplayName => "Weights & Biases";public override ConnectionStrategyCapabilities Capabilities => new(SupportsPooling: false, SupportsStreaming: false, SupportsAuthentication: true);public override string SemanticDescription => "Weights & Biases ML experiment tracking platform. Run logging, artifact management, sweeps, and model registry.";public override string[] Tags => ["wandb", "weights-biases", "experiment-tracking", "ml-ops", "artifacts"];
    public WeightsAndBiasesConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var baseUrl = config.ConnectionString ?? "https://api.wandb.ai";var httpClient = new HttpClient { BaseAddress = new Uri(baseUrl), Timeout = config.Timeout };if (config.Properties.TryGetValue("ApiKey", out var apiKey)){httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", apiKey.ToString()!);}return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "W&B", ["BaseUrl"] = baseUrl });}
    protected override async Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct){var httpClient = handle.GetConnection<HttpClient>();var query = JsonSerializer.Serialize(new { query = "{ viewer { id } }" });var content = new StringContent(query, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync("/graphql", content, ct);return response.IsSuccessStatusCode;}
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override async Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct){var httpClient = handle.GetConnection<HttpClient>();try{var query = JsonSerializer.Serialize(new { query = "{ viewer { id username } }" });var content = new StringContent(query, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync("/graphql", content, ct);return new ConnectionHealth(response.IsSuccessStatusCode, response.IsSuccessStatusCode ? "W&B connected" : "W&B unreachable", TimeSpan.Zero, DateTimeOffset.UtcNow);}catch (Exception ex){return new ConnectionHealth(false, $"W&B error: {ex.Message}", TimeSpan.Zero, DateTimeOffset.UtcNow);}}
    public override async Task<string> SendRequestAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var action = options?.GetValueOrDefault("action", "graphql")?.ToString() ?? "graphql";if (action == "graphql"){var json = JsonSerializer.Serialize(new { query = prompt });var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync("/graphql", content, ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}else if (action == "log"){var entity = options?.GetValueOrDefault("entity", "")?.ToString();var project = options?.GetValueOrDefault("project", "")?.ToString();var runId = options?.GetValueOrDefault("run_id", "")?.ToString();var data = (options?.TryGetValue("data", out var dataVal) == true ? dataVal : null);var json = JsonSerializer.Serialize(data);var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync($"/files/{entity}/{project}/{runId}/file_stream", content, ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}else{var json = JsonSerializer.Serialize(new { query = "{ viewer { id username teams { edges { node { name } } } } }" });var content = new StringContent(json, Encoding.UTF8, "application/json");var response = await httpClient.PostAsync("/graphql", content, ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}}
    public override async IAsyncEnumerable<string> StreamResponseAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, [EnumeratorCancellation] CancellationToken ct = default){throw new NotSupportedException("Weights & Biases does not support streaming responses. Use SendRequestAsync for experiment management.");yield break;}
}
