using System;using System.Collections.Generic;using System.Net.Http;using System.Net.Http.Headers;using System.Runtime.CompilerServices;using System.Text;using System.Text.Json;using System.Threading;using System.Threading.Tasks;using DataWarehouse.SDK.Connectors;using Microsoft.Extensions.Logging;

namespace DataWarehouse.Plugins.UltimateConnector.Strategies.AI;

/// <summary>OpenAI Whisper API. HTTPS to api.openai.com/v1/audio. Speech transcription and translation.</summary>
public sealed class WhisperConnectionStrategy : AiConnectionStrategyBase
{
    public override string StrategyId => "ai-whisper";public override string DisplayName => "OpenAI Whisper";public override ConnectionStrategyCapabilities Capabilities => new(SupportsPooling: false, SupportsStreaming: false, SupportsAuthentication: true);public override string SemanticDescription => "OpenAI Whisper speech recognition API. Audio transcription and translation supporting 97 languages with timestamp generation.";public override string[] Tags => ["whisper", "openai", "stt", "speech-to-text", "transcription", "translation"];
    public WhisperConnectionStrategy(ILogger? logger = null) : base(logger) { }
    protected override async Task<IConnectionHandle> ConnectCoreAsync(ConnectionConfig config, CancellationToken ct){var httpClient = new HttpClient { BaseAddress = new Uri("https://api.openai.com/v1"), Timeout = config.Timeout };if (config.Properties.TryGetValue("ApiKey", out var apiKey)){httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", apiKey.ToString()!);}return new DefaultConnectionHandle(httpClient, new Dictionary<string, object> { ["Provider"] = "Whisper" });}
    protected override Task<bool> TestCoreAsync(IConnectionHandle handle, CancellationToken ct) => Task.FromResult(true);
    protected override Task DisconnectCoreAsync(IConnectionHandle handle, CancellationToken ct){handle.GetConnection<HttpClient>().Dispose();if (handle is DefaultConnectionHandle defaultHandle) defaultHandle.MarkDisconnected();return Task.CompletedTask;}
    protected override Task<ConnectionHealth> GetHealthCoreAsync(IConnectionHandle handle, CancellationToken ct) => Task.FromResult(new ConnectionHealth(true, "Whisper configured", TimeSpan.Zero, DateTimeOffset.UtcNow));
    public override async Task<string> SendRequestAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, CancellationToken ct = default){var httpClient = handle.GetConnection<HttpClient>();var action = options?.GetValueOrDefault("action", "transcribe")?.ToString() ?? "transcribe";var audioBase64 = options?.GetValueOrDefault("audio", prompt)?.ToString() ?? prompt;var audioBytes = Convert.FromBase64String(audioBase64);var formContent = new MultipartFormDataContent();var audioContent = new ByteArrayContent(audioBytes);audioContent.Headers.ContentType = new MediaTypeHeaderValue("audio/wav");formContent.Add(audioContent, "file", "audio.wav");formContent.Add(new StringContent(options?.GetValueOrDefault("model", "whisper-1")?.ToString() ?? "whisper-1"), "model");if (options?.TryGetValue("language", out var lang) == true && lang != null){formContent.Add(new StringContent(lang.ToString()!), "language");}var responseFormat = options?.GetValueOrDefault("response_format", "json")?.ToString() ?? "json";formContent.Add(new StringContent(responseFormat), "response_format");var endpoint = action == "translate" ? "/audio/translations" : "/audio/transcriptions";var response = await httpClient.PostAsync(endpoint, formContent, ct);response.EnsureSuccessStatusCode();return await response.Content.ReadAsStringAsync(ct);}
    public override async IAsyncEnumerable<string> StreamResponseAsync(IConnectionHandle handle, string prompt, Dictionary<string, object>? options = null, [EnumeratorCancellation] CancellationToken ct = default){throw new NotSupportedException("Whisper does not support streaming responses. Use SendRequestAsync for audio transcription/translation.");yield break;}
}
